import 'package:warcrafty/src/core/field_definition.dart';
import 'package:warcrafty/src/core/structure_definition.dart';
import 'package:warcrafty/src/core/field_format.dart';

/// CharStartOutfit 结构定义
///
/// 基于 WoWDBDefs 定义，版本 3.3.5.12340
const charStartOutfit = DbcStructureDefinition(
  name: 'CharStartOutfit',
  format: 'nbbbbiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii',
  fields: [
    FieldDefinition(index: 0, name: 'ID', description: 'ID', format: DbcFieldFormat.indexField),
    FieldDefinition(index: 1, name: 'RaceID', description: 'RaceID', format: DbcFieldFormat.byte),
    FieldDefinition(index: 2, name: 'ClassID', description: 'ClassID', format: DbcFieldFormat.byte),
    FieldDefinition(index: 3, name: 'SexID', description: 'SexID', format: DbcFieldFormat.byte),
    FieldDefinition(index: 4, name: 'OutfitID', description: 'OutfitID', format: DbcFieldFormat.byte),
    FieldDefinition(index: 5, name: 'ItemID0', description: 'ItemID 0', format: DbcFieldFormat.intType),
    FieldDefinition(index: 6, name: 'ItemID1', description: 'ItemID 1', format: DbcFieldFormat.intType),
    FieldDefinition(index: 7, name: 'ItemID2', description: 'ItemID 2', format: DbcFieldFormat.intType),
    FieldDefinition(index: 8, name: 'ItemID3', description: 'ItemID 3', format: DbcFieldFormat.intType),
    FieldDefinition(index: 9, name: 'ItemID4', description: 'ItemID 4', format: DbcFieldFormat.intType),
    FieldDefinition(index: 10, name: 'ItemID5', description: 'ItemID 5', format: DbcFieldFormat.intType),
    FieldDefinition(index: 11, name: 'ItemID6', description: 'ItemID 6', format: DbcFieldFormat.intType),
    FieldDefinition(index: 12, name: 'ItemID7', description: 'ItemID 7', format: DbcFieldFormat.intType),
    FieldDefinition(index: 13, name: 'ItemID8', description: 'ItemID 8', format: DbcFieldFormat.intType),
    FieldDefinition(index: 14, name: 'ItemID9', description: 'ItemID 9', format: DbcFieldFormat.intType),
    FieldDefinition(index: 15, name: 'ItemID10', description: 'ItemID 10', format: DbcFieldFormat.intType),
    FieldDefinition(index: 16, name: 'ItemID11', description: 'ItemID 11', format: DbcFieldFormat.intType),
    FieldDefinition(index: 17, name: 'ItemID12', description: 'ItemID 12', format: DbcFieldFormat.intType),
    FieldDefinition(index: 18, name: 'ItemID13', description: 'ItemID 13', format: DbcFieldFormat.intType),
    FieldDefinition(index: 19, name: 'ItemID14', description: 'ItemID 14', format: DbcFieldFormat.intType),
    FieldDefinition(index: 20, name: 'ItemID15', description: 'ItemID 15', format: DbcFieldFormat.intType),
    FieldDefinition(index: 21, name: 'ItemID16', description: 'ItemID 16', format: DbcFieldFormat.intType),
    FieldDefinition(index: 22, name: 'ItemID17', description: 'ItemID 17', format: DbcFieldFormat.intType),
    FieldDefinition(index: 23, name: 'ItemID18', description: 'ItemID 18', format: DbcFieldFormat.intType),
    FieldDefinition(index: 24, name: 'ItemID19', description: 'ItemID 19', format: DbcFieldFormat.intType),
    FieldDefinition(index: 25, name: 'ItemID20', description: 'ItemID 20', format: DbcFieldFormat.intType),
    FieldDefinition(index: 26, name: 'ItemID21', description: 'ItemID 21', format: DbcFieldFormat.intType),
    FieldDefinition(index: 27, name: 'ItemID22', description: 'ItemID 22', format: DbcFieldFormat.intType),
    FieldDefinition(index: 28, name: 'ItemID23', description: 'ItemID 23', format: DbcFieldFormat.intType),
    FieldDefinition(index: 29, name: 'DisplayItemID0', description: 'DisplayItemID 0', format: DbcFieldFormat.intType),
    FieldDefinition(index: 30, name: 'DisplayItemID1', description: 'DisplayItemID 1', format: DbcFieldFormat.intType),
    FieldDefinition(index: 31, name: 'DisplayItemID2', description: 'DisplayItemID 2', format: DbcFieldFormat.intType),
    FieldDefinition(index: 32, name: 'DisplayItemID3', description: 'DisplayItemID 3', format: DbcFieldFormat.intType),
    FieldDefinition(index: 33, name: 'DisplayItemID4', description: 'DisplayItemID 4', format: DbcFieldFormat.intType),
    FieldDefinition(index: 34, name: 'DisplayItemID5', description: 'DisplayItemID 5', format: DbcFieldFormat.intType),
    FieldDefinition(index: 35, name: 'DisplayItemID6', description: 'DisplayItemID 6', format: DbcFieldFormat.intType),
    FieldDefinition(index: 36, name: 'DisplayItemID7', description: 'DisplayItemID 7', format: DbcFieldFormat.intType),
    FieldDefinition(index: 37, name: 'DisplayItemID8', description: 'DisplayItemID 8', format: DbcFieldFormat.intType),
    FieldDefinition(index: 38, name: 'DisplayItemID9', description: 'DisplayItemID 9', format: DbcFieldFormat.intType),
    FieldDefinition(index: 39, name: 'DisplayItemID10', description: 'DisplayItemID 10', format: DbcFieldFormat.intType),
    FieldDefinition(index: 40, name: 'DisplayItemID11', description: 'DisplayItemID 11', format: DbcFieldFormat.intType),
    FieldDefinition(index: 41, name: 'DisplayItemID12', description: 'DisplayItemID 12', format: DbcFieldFormat.intType),
    FieldDefinition(index: 42, name: 'DisplayItemID13', description: 'DisplayItemID 13', format: DbcFieldFormat.intType),
    FieldDefinition(index: 43, name: 'DisplayItemID14', description: 'DisplayItemID 14', format: DbcFieldFormat.intType),
    FieldDefinition(index: 44, name: 'DisplayItemID15', description: 'DisplayItemID 15', format: DbcFieldFormat.intType),
    FieldDefinition(index: 45, name: 'DisplayItemID16', description: 'DisplayItemID 16', format: DbcFieldFormat.intType),
    FieldDefinition(index: 46, name: 'DisplayItemID17', description: 'DisplayItemID 17', format: DbcFieldFormat.intType),
    FieldDefinition(index: 47, name: 'DisplayItemID18', description: 'DisplayItemID 18', format: DbcFieldFormat.intType),
    FieldDefinition(index: 48, name: 'DisplayItemID19', description: 'DisplayItemID 19', format: DbcFieldFormat.intType),
    FieldDefinition(index: 49, name: 'DisplayItemID20', description: 'DisplayItemID 20', format: DbcFieldFormat.intType),
    FieldDefinition(index: 50, name: 'DisplayItemID21', description: 'DisplayItemID 21', format: DbcFieldFormat.intType),
    FieldDefinition(index: 51, name: 'DisplayItemID22', description: 'DisplayItemID 22', format: DbcFieldFormat.intType),
    FieldDefinition(index: 52, name: 'DisplayItemID23', description: 'DisplayItemID 23', format: DbcFieldFormat.intType),
    FieldDefinition(index: 53, name: 'InventoryType0', description: 'InventoryType 0', format: DbcFieldFormat.intType),
    FieldDefinition(index: 54, name: 'InventoryType1', description: 'InventoryType 1', format: DbcFieldFormat.intType),
    FieldDefinition(index: 55, name: 'InventoryType2', description: 'InventoryType 2', format: DbcFieldFormat.intType),
    FieldDefinition(index: 56, name: 'InventoryType3', description: 'InventoryType 3', format: DbcFieldFormat.intType),
    FieldDefinition(index: 57, name: 'InventoryType4', description: 'InventoryType 4', format: DbcFieldFormat.intType),
    FieldDefinition(index: 58, name: 'InventoryType5', description: 'InventoryType 5', format: DbcFieldFormat.intType),
    FieldDefinition(index: 59, name: 'InventoryType6', description: 'InventoryType 6', format: DbcFieldFormat.intType),
    FieldDefinition(index: 60, name: 'InventoryType7', description: 'InventoryType 7', format: DbcFieldFormat.intType),
    FieldDefinition(index: 61, name: 'InventoryType8', description: 'InventoryType 8', format: DbcFieldFormat.intType),
    FieldDefinition(index: 62, name: 'InventoryType9', description: 'InventoryType 9', format: DbcFieldFormat.intType),
    FieldDefinition(index: 63, name: 'InventoryType10', description: 'InventoryType 10', format: DbcFieldFormat.intType),
    FieldDefinition(index: 64, name: 'InventoryType11', description: 'InventoryType 11', format: DbcFieldFormat.intType),
    FieldDefinition(index: 65, name: 'InventoryType12', description: 'InventoryType 12', format: DbcFieldFormat.intType),
    FieldDefinition(index: 66, name: 'InventoryType13', description: 'InventoryType 13', format: DbcFieldFormat.intType),
    FieldDefinition(index: 67, name: 'InventoryType14', description: 'InventoryType 14', format: DbcFieldFormat.intType),
    FieldDefinition(index: 68, name: 'InventoryType15', description: 'InventoryType 15', format: DbcFieldFormat.intType),
    FieldDefinition(index: 69, name: 'InventoryType16', description: 'InventoryType 16', format: DbcFieldFormat.intType),
    FieldDefinition(index: 70, name: 'InventoryType17', description: 'InventoryType 17', format: DbcFieldFormat.intType),
    FieldDefinition(index: 71, name: 'InventoryType18', description: 'InventoryType 18', format: DbcFieldFormat.intType),
    FieldDefinition(index: 72, name: 'InventoryType19', description: 'InventoryType 19', format: DbcFieldFormat.intType),
    FieldDefinition(index: 73, name: 'InventoryType20', description: 'InventoryType 20', format: DbcFieldFormat.intType),
    FieldDefinition(index: 74, name: 'InventoryType21', description: 'InventoryType 21', format: DbcFieldFormat.intType),
    FieldDefinition(index: 75, name: 'InventoryType22', description: 'InventoryType 22', format: DbcFieldFormat.intType),
    FieldDefinition(index: 76, name: 'InventoryType23', description: 'InventoryType 23', format: DbcFieldFormat.intType),
  ],
);
