import 'package:warcrafty/src/core/field_definition.dart';
import 'package:warcrafty/src/core/structure_definition.dart';
import 'package:warcrafty/src/core/field_format.dart';

/// VehicleSeat 结构定义
///
/// 基于 WoWDBDefs 定义，版本 3.3.5.12340
const vehicleSeat = DbcStructureDefinition(
  name: 'VehicleSeat',
  format: 'nfiffffffffffiiiiiifffffffiiifffiiiiiiiffiiiifffifffffffff',
  fields: [
    FieldDefinition(index: 0, name: 'ID', description: 'ID', format: DbcFieldFormat.indexField),
    FieldDefinition(index: 1, name: 'Field_3_3_5_12213_001', description: 'Field_3_3_5_12213_001', format: DbcFieldFormat.float),
    FieldDefinition(index: 2, name: 'AttachmentID', description: 'AttachmentID', format: DbcFieldFormat.intType),
    FieldDefinition(index: 3, name: 'AttachmentOffset0', description: 'AttachmentOffset 0', format: DbcFieldFormat.float),
    FieldDefinition(index: 4, name: 'AttachmentOffset1', description: 'AttachmentOffset 1', format: DbcFieldFormat.float),
    FieldDefinition(index: 5, name: 'AttachmentOffset2', description: 'AttachmentOffset 2', format: DbcFieldFormat.float),
    FieldDefinition(index: 6, name: 'Field_3_3_5_12213_004', description: 'Field_3_3_5_12213_004', format: DbcFieldFormat.float),
    FieldDefinition(index: 7, name: 'EnterSpeed', description: 'EnterSpeed', format: DbcFieldFormat.float),
    FieldDefinition(index: 8, name: 'EnterGravity', description: 'EnterGravity', format: DbcFieldFormat.float),
    FieldDefinition(index: 9, name: 'EnterMinDuration', description: 'EnterMinDuration', format: DbcFieldFormat.float),
    FieldDefinition(index: 10, name: 'EnterMaxDuration', description: 'EnterMaxDuration', format: DbcFieldFormat.float),
    FieldDefinition(index: 11, name: 'EnterMinArcHeight', description: 'EnterMinArcHeight', format: DbcFieldFormat.float),
    FieldDefinition(index: 12, name: 'EnterMaxArcHeight', description: 'EnterMaxArcHeight', format: DbcFieldFormat.float),
    FieldDefinition(index: 13, name: 'EnterAnimStart', description: 'EnterAnimStart', format: DbcFieldFormat.intType),
    FieldDefinition(index: 14, name: 'EnterAnimLoop', description: 'EnterAnimLoop', format: DbcFieldFormat.intType),
    FieldDefinition(index: 15, name: 'RideAnimStart', description: 'RideAnimStart', format: DbcFieldFormat.intType),
    FieldDefinition(index: 16, name: 'RideAnimLoop', description: 'RideAnimLoop', format: DbcFieldFormat.intType),
    FieldDefinition(index: 17, name: 'RideUpperAnimStart', description: 'RideUpperAnimStart', format: DbcFieldFormat.intType),
    FieldDefinition(index: 18, name: 'RideUpperAnimLoop', description: 'RideUpperAnimLoop', format: DbcFieldFormat.intType),
    FieldDefinition(index: 19, name: 'Field_3_3_5_12213_017', description: 'Field_3_3_5_12213_017', format: DbcFieldFormat.float),
    FieldDefinition(index: 20, name: 'ExitSpeed', description: 'ExitSpeed', format: DbcFieldFormat.float),
    FieldDefinition(index: 21, name: 'ExitGravity', description: 'ExitGravity', format: DbcFieldFormat.float),
    FieldDefinition(index: 22, name: 'ExitMinDuration', description: 'ExitMinDuration', format: DbcFieldFormat.float),
    FieldDefinition(index: 23, name: 'ExitMaxDuration', description: 'ExitMaxDuration', format: DbcFieldFormat.float),
    FieldDefinition(index: 24, name: 'ExitMinArcHeight', description: 'ExitMinArcHeight', format: DbcFieldFormat.float),
    FieldDefinition(index: 25, name: 'ExitMaxArcHeight', description: 'ExitMaxArcHeight', format: DbcFieldFormat.float),
    FieldDefinition(index: 26, name: 'ExitAnimStart', description: 'ExitAnimStart', format: DbcFieldFormat.intType),
    FieldDefinition(index: 27, name: 'ExitAnimLoop', description: 'ExitAnimLoop', format: DbcFieldFormat.intType),
    FieldDefinition(index: 28, name: 'ExitAnimEnd', description: 'ExitAnimEnd', format: DbcFieldFormat.intType),
    FieldDefinition(index: 29, name: 'Field_3_3_5_12213_027', description: 'Field_3_3_5_12213_027', format: DbcFieldFormat.float),
    FieldDefinition(index: 30, name: 'PassengerPitch', description: 'PassengerPitch', format: DbcFieldFormat.float),
    FieldDefinition(index: 31, name: 'Field_3_3_5_12213_029', description: 'Field_3_3_5_12213_029', format: DbcFieldFormat.float),
    FieldDefinition(index: 32, name: 'PassengerAttachmentID', description: 'PassengerAttachmentID', format: DbcFieldFormat.intType),
    FieldDefinition(index: 33, name: 'VehicleEnterAnim', description: 'VehicleEnterAnim', format: DbcFieldFormat.intType),
    FieldDefinition(index: 34, name: 'VehicleExitAnim', description: 'VehicleExitAnim', format: DbcFieldFormat.intType),
    FieldDefinition(index: 35, name: 'VehicleRideAnimLoop', description: 'VehicleRideAnimLoop', format: DbcFieldFormat.intType),
    FieldDefinition(index: 36, name: 'Field_3_3_5_12213_034', description: 'Field_3_3_5_12213_034', format: DbcFieldFormat.intType),
    FieldDefinition(index: 37, name: 'VehicleExitAnimBone', description: 'VehicleExitAnimBone', format: DbcFieldFormat.intType),
    FieldDefinition(index: 38, name: 'VehicleEnterAnimBone', description: 'VehicleEnterAnimBone', format: DbcFieldFormat.intType),
    FieldDefinition(index: 39, name: 'Field_3_3_5_12213_037', description: 'Field_3_3_5_12213_037', format: DbcFieldFormat.float),
    FieldDefinition(index: 40, name: 'Field_3_3_5_12213_038', description: 'Field_3_3_5_12213_038', format: DbcFieldFormat.float),
    FieldDefinition(index: 41, name: 'VehicleAbilityDisplay', description: 'VehicleAbilityDisplay', format: DbcFieldFormat.intType),
    FieldDefinition(index: 42, name: 'EnterUISoundID', description: 'EnterUISoundID', format: DbcFieldFormat.intType),
    FieldDefinition(index: 43, name: 'Field_3_3_5_12213_041', description: 'Field_3_3_5_12213_041', format: DbcFieldFormat.intType),
    FieldDefinition(index: 44, name: 'UiSkin', description: 'UiSkin', format: DbcFieldFormat.intType),
    FieldDefinition(index: 45, name: 'Field_3_3_5_12213_043', description: 'Field_3_3_5_12213_043', format: DbcFieldFormat.float),
    FieldDefinition(index: 46, name: 'Field_3_3_5_12213_044', description: 'Field_3_3_5_12213_044', format: DbcFieldFormat.float),
    FieldDefinition(index: 47, name: 'Field_3_3_5_12213_045', description: 'Field_3_3_5_12213_045', format: DbcFieldFormat.float),
    FieldDefinition(index: 48, name: 'Field_3_3_5_12213_046', description: 'Field_3_3_5_12213_046', format: DbcFieldFormat.intType),
    FieldDefinition(index: 49, name: 'Field_3_3_5_12213_047', description: 'Field_3_3_5_12213_047', format: DbcFieldFormat.float),
    FieldDefinition(index: 50, name: 'Field_3_3_5_12213_048', description: 'Field_3_3_5_12213_048', format: DbcFieldFormat.float),
    FieldDefinition(index: 51, name: 'Field_3_3_5_12213_049', description: 'Field_3_3_5_12213_049', format: DbcFieldFormat.float),
    FieldDefinition(index: 52, name: 'Field_3_3_5_12213_050', description: 'Field_3_3_5_12213_050', format: DbcFieldFormat.float),
    FieldDefinition(index: 53, name: 'Field_3_3_5_12213_051', description: 'Field_3_3_5_12213_051', format: DbcFieldFormat.float),
    FieldDefinition(index: 54, name: 'Field_3_3_5_12213_052', description: 'Field_3_3_5_12213_052', format: DbcFieldFormat.float),
    FieldDefinition(index: 55, name: 'Field_3_3_5_12213_053', description: 'Field_3_3_5_12213_053', format: DbcFieldFormat.float),
    FieldDefinition(index: 56, name: 'Field_3_3_5_12213_054', description: 'Field_3_3_5_12213_054', format: DbcFieldFormat.float),
    FieldDefinition(index: 57, name: 'Field_3_3_5_12213_055', description: 'Field_3_3_5_12213_055', format: DbcFieldFormat.float),
  ],
);
