import 'package:warcrafty/src/schema/field.dart';
import 'package:warcrafty/src/schema/schema.dart';

/// Vehicle 结构定义
///
/// 基于 WoWDBDefs 定义，版本 3.3.5.12340
const vehicle = DbcSchema(
  name: 'Vehicle',
  format: 'niffffiiiiiiiifffffffffffffffssssfifiiii',
  fields: [
    Field(index: 0, name: 'ID', description: 'ID', type: FieldType.id),
    Field(index: 1, name: 'Flags', description: 'Flags', type: FieldType.int32),
    Field(index: 2, name: 'TurnSpeed', description: 'TurnSpeed', type: FieldType.float),
    Field(index: 3, name: 'PitchSpeed', description: 'PitchSpeed', type: FieldType.float),
    Field(index: 4, name: 'PitchMin', description: 'PitchMin', type: FieldType.float),
    Field(index: 5, name: 'PitchMax', description: 'PitchMax', type: FieldType.float),
    Field(index: 6, name: 'SeatID0', description: 'SeatID 0', type: FieldType.int32),
    Field(index: 7, name: 'SeatID1', description: 'SeatID 1', type: FieldType.int32),
    Field(index: 8, name: 'SeatID2', description: 'SeatID 2', type: FieldType.int32),
    Field(index: 9, name: 'SeatID3', description: 'SeatID 3', type: FieldType.int32),
    Field(index: 10, name: 'SeatID4', description: 'SeatID 4', type: FieldType.int32),
    Field(index: 11, name: 'SeatID5', description: 'SeatID 5', type: FieldType.int32),
    Field(index: 12, name: 'SeatID6', description: 'SeatID 6', type: FieldType.int32),
    Field(index: 13, name: 'SeatID7', description: 'SeatID 7', type: FieldType.int32),
    Field(index: 14, name: 'MouseLookOffsetPitch', description: 'MouseLookOffsetPitch', type: FieldType.float),
    Field(index: 15, name: 'CameraFadeDistScalarMin', description: 'CameraFadeDistScalarMin', type: FieldType.float),
    Field(index: 16, name: 'CameraFadeDistScalarMax', description: 'CameraFadeDistScalarMax', type: FieldType.float),
    Field(index: 17, name: 'CameraPitchOffset', description: 'CameraPitchOffset', type: FieldType.float),
    Field(index: 18, name: 'FacingLimitRight', description: 'FacingLimitRight', type: FieldType.float),
    Field(index: 19, name: 'FacingLimitLeft', description: 'FacingLimitLeft', type: FieldType.float),
    Field(index: 20, name: 'MsslTrgtTurnLingering', description: 'MsslTrgtTurnLingering', type: FieldType.float),
    Field(index: 21, name: 'MsslTrgtPitchLingering', description: 'MsslTrgtPitchLingering', type: FieldType.float),
    Field(index: 22, name: 'MsslTrgtMouseLingering', description: 'MsslTrgtMouseLingering', type: FieldType.float),
    Field(index: 23, name: 'MsslTrgtEndOpacity', description: 'MsslTrgtEndOpacity', type: FieldType.float),
    Field(index: 24, name: 'MsslTrgtArcSpeed', description: 'MsslTrgtArcSpeed', type: FieldType.float),
    Field(index: 25, name: 'MsslTrgtArcRepeat', description: 'MsslTrgtArcRepeat', type: FieldType.float),
    Field(index: 26, name: 'MsslTrgtArcWidth', description: 'MsslTrgtArcWidth', type: FieldType.float),
    Field(index: 27, name: 'MsslTrgtImpactRadius0', description: 'MsslTrgtImpactRadius 0', type: FieldType.float),
    Field(index: 28, name: 'MsslTrgtImpactRadius1', description: 'MsslTrgtImpactRadius 1', type: FieldType.float),
    Field(index: 29, name: 'MsslTrgtArcTexture', description: 'MsslTrgtArcTexture', type: FieldType.string),
    Field(index: 30, name: 'MsslTrgtImpactTexture', description: 'MsslTrgtImpactTexture', type: FieldType.string),
    Field(index: 31, name: 'MsslTrgtImpactModel0', description: 'MsslTrgtImpactModel 0', type: FieldType.string),
    Field(index: 32, name: 'MsslTrgtImpactModel1', description: 'MsslTrgtImpactModel 1', type: FieldType.string),
    Field(index: 33, name: 'CameraYawOffset', description: 'CameraYawOffset', type: FieldType.float),
    Field(index: 34, name: 'UiLocomotionType', description: 'UiLocomotionType', type: FieldType.int32),
    Field(index: 35, name: 'MsslTrgtImpactTexRadius', description: 'MsslTrgtImpactTexRadius', type: FieldType.float),
    Field(index: 36, name: 'VehicleUIIndicatorID', description: 'VehicleUIIndicatorID', type: FieldType.int32),
    Field(index: 37, name: 'PowerDisplayID0', description: 'PowerDisplayID 0', type: FieldType.int32),
    Field(index: 38, name: 'PowerDisplayID1', description: 'PowerDisplayID 1', type: FieldType.int32),
    Field(index: 39, name: 'PowerDisplayID2', description: 'PowerDisplayID 2', type: FieldType.int32),
  ],
);
