const t = require("../lib/types");

module.exports = {
  id: t.int32le,
  continentId: t.int32le,
  parentAreaId: t.int32le,
  areaBit: t.int32le,
  flags: t.int32le,
  soundPrividerPref: t.int32le,
  soundPrividerPrefUnderwater: t.int32le,
  ambienceId: t.int32le,
  zoneMusic: t.int32le,
  introSound: t.int32le,
  explorationLevel: t.int32le,
  areaNameLangEnUS: t.string,
  areaNameLangEnGB: t.string,
  areaNameLangDeDE: t.string,
  areaNameLangEnCN: t.string,
  areaNameLangZhCN: t.string,
  areaNameLangEnTW: t.string,
  areaNameLangZhTW: t.string,
  areaNameLangEsES: t.string,
  areaNameLangEsMX: t.string,
  areaNameLangKoKR: t.string,
  areaNameLangFrFR: t.string,
  areaNameLangRuRU: t.string,
  areaNameLangPtPT: t.string,
  areaNameLangPtBR: t.string,
  areaNameLangItIT: t.string,
  areaNameLangUnk: t.string,
  areaNameLangMask: t.int32le,
  factionGroupMask: t.int32le,
  liquidTypeId1: t.int32le,
  liquidTypeId2: t.int32le,
  liquidTypeId3: t.int32le,
  liquidTypeId4: t.int32le,
  minElevation: t.float32le,
  ambientMultiplier: t.float32le,
  ligntId: t.int32le,
};
