const t = require("../lib/types");

module.exports = {
  id: t.LONG,
  unk_2: t.LONG,
  unk_3: t.LONG,
  unk_4: t.LONG,
  unk_5: t.FLAGS,
  unk_6: t.LONG,
  unk_7: t.LONG,
  unk_8: t.LONG,
  unk_9: t.LONG,
  unk_10: t.LONG,
  unk_11: t.LONG,
  unk_12: t.NONE,
  unk_13: t.NONE,
  unk_14: t.NONE,
  unk_15: t.NONE,
  unk_16: t.STRING,
  unk_17: t.NONE,
  unk_18: t.NONE,
  unk_19: t.NONE,
  unk_20: t.NONE,
  unk_21: t.NONE,
  unk_22: t.NONE,
  unk_23: t.NONE,
  unk_24: t.NONE,
  unk_25: t.NONE,
  unk_26: t.NONE,
  unk_27: t.NONE,
  unk_28: t.FLAGS,
  unk_29: t.FLAGS,
  unk_30: t.LONG,
  unk_31: t.NONE,
  unk_32: t.NONE,
  unk_33: t.LONG,
  unk_34: t.FLOAT,
  unk_35: t.FLOAT,
  unk_36: t.NONE,
};
