const t = require("../lib/types");

module.exports = {
  id: t.LONG,
  continentId: t.LONG,
  parentAreaId: t.LONG,
  areaBit: t.LONG,
  flags: t.FLAGS,
  soundProviderPref: t.LONG,
  soundProviderPrefUnderwater: t.LONG,
  ambienceId: t.LONG,
  zoonMusic: t.LONG,
  introSound: t.LONG,
  explorationLevel: t.LONG,
  areaNameLangEnUS: t.STRING,
  areaNameLangEnGB: t.STRING,
  areaNameLangDeDE: t.STRING,
  areaNameLangEnCN: t.STRING,
  areaNameLangZhCN: t.STRING,
  areaNameLangEnTW: t.STRING,
  areaNameLangZhTW: t.STRING,
  areaNameLangEsES: t.STRING,
  areaNameLangEsMX: t.STRING,
  areaNameLangKoKR: t.STRING,
  areaNameLangFrFR: t.STRING,
  areaNameLangRuRU: t.STRING,
  areaNameLangPtPT: t.STRING,
  areaNameLangPtBR: t.STRING,
  areaNameLangitIT: t.STRING,
  areaNameLangUnk: t.STRING,
  areaNameLangMask: t.FLAGS,
  factionGroupMask: t.FLAGS,
  liquidTypeId1: t.LONG,
  liquidTypeId2: t.LONG,
  liquidTypeId3: t.LONG,
  liquidTypeId4: t.LONG,
  minElevation: t.FLOAT,
  ambientMultiplier: t.FLOAT,
  lightId: t.LONG,
};
