const t = require("../lib/types");

module.exports = {
  id: t.LONG,
  mapId1: t.LONG,
  mapId2: t.LONG,
  mapId3: t.LONG,
  mapId4: t.LONG,
  mapId5: t.LONG,
  mapId6: t.LONG,
  mapId7: t.LONG,
  mapId8: t.LONG,
  instanceType: t.LONG,
  groupAllowed: t.BOOL,
  nameLangEnUS: t.STRING,
  nameLangEnGB: t.STRING,
  nameLangDeDE: t.STRING,
  nameLangEnCN: t.STRING,
  nameLangZhCN: t.STRING,
  nameLangEnTW: t.STRING,
  nameLangZhTW: t.STRING,
  nameLangEsES: t.STRING,
  nameLangEsMX: t.STRING,
  nameLangKoKR: t.STRING,
  nameLangFrFR: t.STRING,
  nameLangRuRU: t.STRING,
  nameLangPtPT: t.STRING,
  nameLangPtBR: t.STRING,
  nameLangitIT: t.STRING,
  nameLangUnk: t.STRING,
  nameLangMask: t.FLAGS,
  maxGroupSize: t.LONG,
  holidayWorldState: t.LONG,
  minLevel: t.LONG,
  maxLevel: t.FLAGS,
};
