const t = require("../lib/types");

module.exports = {
  id: t.LONG,
  conditionId: t.LONG,
  nameLangEnUS: t.STRING,
  nameLangEnGB: t.STRING,
  nameLangDeDE: t.STRING,
  nameLangEnCN: t.STRING,
  nameLangZhCN: t.STRING,
  nameLangEnTW: t.STRING,
  nameLangZhTW: t.STRING,
  nameLangEsES: t.STRING,
  nameLangEsMX: t.STRING,
  nameLangKoKR: t.STRING,
  nameLangFrFR: t.STRING,
  nameLangRuRU: t.STRING,
  nameLangPtPT: t.STRING,
  nameLangPtBR: t.STRING,
  nameLangitIT: t.STRING,
  nameLangUnk: t.STRING,
  nameLangMask: t.FLAGS,
  name1LangEnUS: t.STRING,
  name1LangEnGB: t.STRING,
  name1LangDeDE: t.STRING,
  name1LangEnCN: t.STRING,
  name1LangZhCN: t.STRING,
  name1LangEnTW: t.STRING,
  name1LangZhTW: t.STRING,
  name1LangEsES: t.STRING,
  name1LangEsMX: t.STRING,
  name1LangKoKR: t.STRING,
  name1LangFrFR: t.STRING,
  name1LangRuRU: t.STRING,
  name1LangPtPT: t.STRING,
  name1LangPtBR: t.STRING,
  name1LangitIT: t.STRING,
  name1LangUnk: t.STRING,
  name1LangMask: t.FLAGS,
  maskId: t.LONG,
};
