const t = require("../lib/types");

module.exports = {
  id: t.LONG,
  unk_2: t.LONG,
  unk_3: t.LONG,
  unk_4: t.BOOL,
  unk_5: t.FLAGS,
  unk_6: t.STRING,
  unk_7: t.NONE,
  unk_8: t.NONE,
  unk_9: t.NONE,
  unk_10: t.NONE,
  unk_11: t.STRING,
  unk_12: t.NONE,
  unk_13: t.NONE,
  unk_14: t.NONE,
  unk_15: t.NONE,
  unk_16: t.NONE,
  unk_17: t.NONE,
  unk_18: t.NONE,
  unk_19: t.NONE,
  unk_20: t.NONE,
  unk_21: t.NONE,
  unk_22: t.NONE,
  unk_23: t.FLAGS,
  unk_24: t.LONG,
};
