const t = require("../lib/types");

module.exports = {
  ID: t.int32le,
  RangeMin_1: t.float32le,
  RangeMin_2: t.float32le,
  RangeMax_1: t.float32le,
  RangeMax_2: t.float32le,
  Flags: t.int32le,
  DisplayName_Lang_enUS: t.string,
  DisplayName_Lang_enGB: t.string,
  DisplayName_Lang_koKR: t.string,
  DisplayName_Lang_frFR: t.string,
  DisplayName_Lang_zhCN: t.string,
  DisplayName_Lang_enCN: t.string,
  DisplayName_Lang_deDE: t.string,
  DisplayName_Lang_enTW: t.string,
  DisplayName_Lang_zhTW: t.string,
  DisplayName_Lang_esES: t.string,
  DisplayName_Lang_esMX: t.string,
  DisplayName_Lang_ruRU: t.string,
  DisplayName_Lang_ptPT: t.string,
  DisplayName_Lang_ptBR: t.string,
  DisplayName_Lang_itIT: t.string,
  DisplayName_Lang_Unk: t.string,
  DisplayName_Lang_Mask: t.int32le,
  DisplayNameShort_Lang_enUS: t.string,
  DisplayNameShort_Lang_enGB: t.string,
  DisplayNameShort_Lang_koKR: t.string,
  DisplayNameShort_Lang_frFR: t.string,
  DisplayNameShort_Lang_zhCN: t.string,
  DisplayNameShort_Lang_enCN: t.string,
  DisplayNameShort_Lang_deDE: t.string,
  DisplayNameShort_Lang_enTW: t.string,
  DisplayNameShort_Lang_zhTW: t.string,
  DisplayNameShort_Lang_esES: t.string,
  DisplayNameShort_Lang_esMX: t.string,
  DisplayNameShort_Lang_ruRU: t.string,
  DisplayNameShort_Lang_ptPT: t.string,
  DisplayNameShort_Lang_ptBR: t.string,
  DisplayNameShort_Lang_itIT: t.string,
  DisplayNameShort_Lang_Unk: t.string,
  DisplayNameShort_Lang_Mask: t.int32le,
};
