// 自动生成的导出文件
// 基于 WoWDBDefs 生成，版本 3.3.5.12340

// achievement
import 'achievement/achievement.dart' as struct_achievement;
import 'achievement/achievement__category.dart' as struct_achievement__category;
import 'achievement/achievement__criteria.dart' as struct_achievement__criteria;

// area
import 'area/area_group.dart' as struct_area_group;
import 'area/area_p_o_i.dart' as struct_area_p_o_i;
import 'area/area_table.dart' as struct_area_table;
import 'area/area_trigger.dart' as struct_area_trigger;
import 'area/w_m_o_area_table.dart' as struct_w_m_o_area_table;
import 'area/world_chunk_sounds.dart' as struct_world_chunk_sounds;
import 'area/world_map_area.dart' as struct_world_map_area;
import 'area/world_map_continent.dart' as struct_world_map_continent;
import 'area/world_map_overlay.dart' as struct_world_map_overlay;
import 'area/world_map_transforms.dart' as struct_world_map_transforms;
import 'area/world_safe_locs.dart' as struct_world_safe_locs;
import 'area/world_state_u_i.dart' as struct_world_state_u_i;
import 'area/world_state_zone_sounds.dart' as struct_world_state_zone_sounds;

// character
import 'character/char_base_info.dart' as struct_char_base_info;
import 'character/char_hair_geosets.dart' as struct_char_hair_geosets;
import 'character/char_hair_textures.dart' as struct_char_hair_textures;
import 'character/char_sections.dart' as struct_char_sections;
import 'character/char_start_outfit.dart' as struct_char_start_outfit;
import 'character/char_titles.dart' as struct_char_titles;
import 'character/character_facial_hair_styles.dart' as struct_character_facial_hair_styles;
import 'character/chat_channels.dart' as struct_chat_channels;
import 'character/chat_profanity.dart' as struct_chat_profanity;
import 'character/chr_classes.dart' as struct_chr_classes;
import 'character/chr_races.dart' as struct_chr_races;

// creature
import 'creature/creature_display_info.dart' as struct_creature_display_info;
import 'creature/creature_display_info_extra.dart' as struct_creature_display_info_extra;
import 'creature/creature_family.dart' as struct_creature_family;
import 'creature/creature_model_data.dart' as struct_creature_model_data;
import 'creature/creature_movement_info.dart' as struct_creature_movement_info;
import 'creature/creature_sound_data.dart' as struct_creature_sound_data;
import 'creature/creature_spell_data.dart' as struct_creature_spell_data;
import 'creature/creature_type.dart' as struct_creature_type;

// faction
import 'faction/faction.dart' as struct_faction;
import 'faction/faction_group.dart' as struct_faction_group;
import 'faction/faction_template.dart' as struct_faction_template;

// gameobject
import 'gameobject/game_object_art_kit.dart' as struct_game_object_art_kit;
import 'gameobject/game_object_display_info.dart' as struct_game_object_display_info;

// item
import 'item/gem_properties.dart' as struct_gem_properties;
import 'item/item.dart' as struct_item;
import 'item/item_bag_family.dart' as struct_item_bag_family;
import 'item/item_class.dart' as struct_item_class;
import 'item/item_cond_ext_costs.dart' as struct_item_cond_ext_costs;
import 'item/item_display_info.dart' as struct_item_display_info;
import 'item/item_extended_cost.dart' as struct_item_extended_cost;
import 'item/item_group_sounds.dart' as struct_item_group_sounds;
import 'item/item_limit_category.dart' as struct_item_limit_category;
import 'item/item_pet_food.dart' as struct_item_pet_food;
import 'item/item_purchase_group.dart' as struct_item_purchase_group;
import 'item/item_random_properties.dart' as struct_item_random_properties;
import 'item/item_random_suffix.dart' as struct_item_random_suffix;
import 'item/item_set.dart' as struct_item_set;
import 'item/item_sub_class.dart' as struct_item_sub_class;
import 'item/item_sub_class_mask.dart' as struct_item_sub_class_mask;
import 'item/item_visual_effects.dart' as struct_item_visual_effects;
import 'item/item_visuals.dart' as struct_item_visuals;

// light
import 'light/light.dart' as struct_light;
import 'light/light_float_band.dart' as struct_light_float_band;
import 'light/light_int_band.dart' as struct_light_int_band;
import 'light/light_params.dart' as struct_light_params;
import 'light/light_skybox.dart' as struct_light_skybox;

// map
import 'map/dungeon_encounter.dart' as struct_dungeon_encounter;
import 'map/dungeon_map.dart' as struct_dungeon_map;
import 'map/dungeon_map_chunk.dart' as struct_dungeon_map_chunk;
import 'map/l_f_g_dungeon_expansion.dart' as struct_l_f_g_dungeon_expansion;
import 'map/l_f_g_dungeon_group.dart' as struct_l_f_g_dungeon_group;
import 'map/l_f_g_dungeons.dart' as struct_l_f_g_dungeons;
import 'map/map.dart' as struct_map;
import 'map/map_difficulty.dart' as struct_map_difficulty;

// misc
import 'misc/animation_data.dart' as struct_animation_data;
import 'misc/attack_anim_kits.dart' as struct_attack_anim_kits;
import 'misc/attack_anim_types.dart' as struct_attack_anim_types;
import 'misc/auction_house.dart' as struct_auction_house;
import 'misc/bank_bag_slot_prices.dart' as struct_bank_bag_slot_prices;
import 'misc/banned_add_ons.dart' as struct_banned_add_ons;
import 'misc/barber_shop_style.dart' as struct_barber_shop_style;
import 'misc/battlemaster_list.dart' as struct_battlemaster_list;
import 'misc/camera_shakes.dart' as struct_camera_shakes;
import 'misc/cfg__categories.dart' as struct_cfg__categories;
import 'misc/cfg__configs.dart' as struct_cfg__configs;
import 'misc/cinematic_camera.dart' as struct_cinematic_camera;
import 'misc/cinematic_sequences.dart' as struct_cinematic_sequences;
import 'misc/currency_category.dart' as struct_currency_category;
import 'misc/currency_types.dart' as struct_currency_types;
import 'misc/dance_moves.dart' as struct_dance_moves;
import 'misc/death_thud_lookups.dart' as struct_death_thud_lookups;
import 'misc/declined_word.dart' as struct_declined_word;
import 'misc/declined_word_cases.dart' as struct_declined_word_cases;
import 'misc/destructible_model_data.dart' as struct_destructible_model_data;
import 'misc/durability_costs.dart' as struct_durability_costs;
import 'misc/durability_quality.dart' as struct_durability_quality;
import 'misc/emotes.dart' as struct_emotes;
import 'misc/emotes_text.dart' as struct_emotes_text;
import 'misc/emotes_text_data.dart' as struct_emotes_text_data;
import 'misc/emotes_text_sound.dart' as struct_emotes_text_sound;
import 'misc/environmental_damage.dart' as struct_environmental_damage;
import 'misc/exhaustion.dart' as struct_exhaustion;
import 'misc/file_data.dart' as struct_file_data;
import 'misc/footprint_textures.dart' as struct_footprint_textures;
import 'misc/footstep_terrain_lookup.dart' as struct_footstep_terrain_lookup;
import 'misc/g_m_survey_answers.dart' as struct_g_m_survey_answers;
import 'misc/g_m_survey_current_survey.dart' as struct_g_m_survey_current_survey;
import 'misc/g_m_survey_questions.dart' as struct_g_m_survey_questions;
import 'misc/g_m_survey_surveys.dart' as struct_g_m_survey_surveys;
import 'misc/g_m_ticket_category.dart' as struct_g_m_ticket_category;
import 'misc/game_tables.dart' as struct_game_tables;
import 'misc/game_tips.dart' as struct_game_tips;
import 'misc/ground_effect_doodad.dart' as struct_ground_effect_doodad;
import 'misc/ground_effect_texture.dart' as struct_ground_effect_texture;
import 'misc/helmet_geoset_vis_data.dart' as struct_helmet_geoset_vis_data;
import 'misc/holiday_descriptions.dart' as struct_holiday_descriptions;
import 'misc/holiday_names.dart' as struct_holiday_names;
import 'misc/holidays.dart' as struct_holidays;
import 'misc/language_words.dart' as struct_language_words;
import 'misc/languages.dart' as struct_languages;
import 'misc/liquid_material.dart' as struct_liquid_material;
import 'misc/liquid_type.dart' as struct_liquid_type;
import 'misc/loading_screen_taxi_splines.dart' as struct_loading_screen_taxi_splines;
import 'misc/loading_screens.dart' as struct_loading_screens;
import 'misc/lock.dart' as struct_lock;
import 'misc/lock_type.dart' as struct_lock_type;
import 'misc/mail_template.dart' as struct_mail_template;
import 'misc/material.dart' as struct_material;
import 'misc/movie.dart' as struct_movie;
import 'misc/movie_file_data.dart' as struct_movie_file_data;
import 'misc/movie_variation.dart' as struct_movie_variation;
import 'misc/n_p_c_sounds.dart' as struct_n_p_c_sounds;
import 'misc/name_gen.dart' as struct_name_gen;
import 'misc/names_profanity.dart' as struct_names_profanity;
import 'misc/names_reserved.dart' as struct_names_reserved;
import 'misc/object_effect.dart' as struct_object_effect;
import 'misc/object_effect_group.dart' as struct_object_effect_group;
import 'misc/object_effect_modifier.dart' as struct_object_effect_modifier;
import 'misc/object_effect_package.dart' as struct_object_effect_package;
import 'misc/object_effect_package_elem.dart' as struct_object_effect_package_elem;
import 'misc/override_spell_data.dart' as struct_override_spell_data;
import 'misc/package.dart' as struct_package;
import 'misc/page_text_material.dart' as struct_page_text_material;
import 'misc/paper_doll_item_frame.dart' as struct_paper_doll_item_frame;
import 'misc/particle_color.dart' as struct_particle_color;
import 'misc/pet_personality.dart' as struct_pet_personality;
import 'misc/petition_type.dart' as struct_petition_type;
import 'misc/power_display.dart' as struct_power_display;
import 'misc/pvp_difficulty.dart' as struct_pvp_difficulty;
import 'misc/rand_prop_points.dart' as struct_rand_prop_points;
import 'misc/resistances.dart' as struct_resistances;
import 'misc/scaling_stat_distribution.dart' as struct_scaling_stat_distribution;
import 'misc/scaling_stat_values.dart' as struct_scaling_stat_values;
import 'misc/screen_effect.dart' as struct_screen_effect;
import 'misc/server_messages.dart' as struct_server_messages;
import 'misc/sheathe_sound_lookups.dart' as struct_sheathe_sound_lookups;
import 'misc/spam_messages.dart' as struct_spam_messages;
import 'misc/stable_slot_prices.dart' as struct_stable_slot_prices;
import 'misc/startup__strings.dart' as struct_startup__strings;
import 'misc/stationery.dart' as struct_stationery;
import 'misc/string_lookups.dart' as struct_string_lookups;
import 'misc/summon_properties.dart' as struct_summon_properties;
import 'misc/team_contribution_points.dart' as struct_team_contribution_points;
import 'misc/terrain_type.dart' as struct_terrain_type;
import 'misc/terrain_type_sounds.dart' as struct_terrain_type_sounds;
import 'misc/transport_animation.dart' as struct_transport_animation;
import 'misc/transport_physics.dart' as struct_transport_physics;
import 'misc/transport_rotation.dart' as struct_transport_rotation;
import 'misc/u_i_sound_lookups.dart' as struct_u_i_sound_lookups;
import 'misc/unit_blood.dart' as struct_unit_blood;
import 'misc/unit_blood_levels.dart' as struct_unit_blood_levels;
import 'misc/video_hardware.dart' as struct_video_hardware;
import 'misc/vocal_u_i_sounds.dart' as struct_vocal_u_i_sounds;
import 'misc/weapon_impact_sounds.dart' as struct_weapon_impact_sounds;
import 'misc/weapon_swing_sounds2.dart' as struct_weapon_swing_sounds2;
import 'misc/weather.dart' as struct_weather;
import 'misc/wow_error__strings.dart' as struct_wow_error__strings;
import 'misc/zone_intro_music_table.dart' as struct_zone_intro_music_table;
import 'misc/zone_music.dart' as struct_zone_music;
import 'misc/gtbarber_shop_cost_base.dart' as struct_gtbarber_shop_cost_base;
import 'misc/gtchance_to_melee_crit.dart' as struct_gtchance_to_melee_crit;
import 'misc/gtchance_to_melee_crit_base.dart' as struct_gtchance_to_melee_crit_base;
import 'misc/gtchance_to_spell_crit.dart' as struct_gtchance_to_spell_crit;
import 'misc/gtchance_to_spell_crit_base.dart' as struct_gtchance_to_spell_crit_base;
import 'misc/gtcombat_ratings.dart' as struct_gtcombat_ratings;
import 'misc/gtn_p_c_mana_cost_scaler.dart' as struct_gtn_p_c_mana_cost_scaler;
import 'misc/gto_c_t_class_combat_rating_scalar.dart' as struct_gto_c_t_class_combat_rating_scalar;
import 'misc/gto_c_t_regen_h_p.dart' as struct_gto_c_t_regen_h_p;
import 'misc/gto_c_t_regen_m_p.dart' as struct_gto_c_t_regen_m_p;
import 'misc/gtregen_h_p_per_spt.dart' as struct_gtregen_h_p_per_spt;
import 'misc/gtregen_m_p_per_spt.dart' as struct_gtregen_m_p_per_spt;

// quest
import 'quest/quest_faction_reward.dart' as struct_quest_faction_reward;
import 'quest/quest_info.dart' as struct_quest_info;
import 'quest/quest_sort.dart' as struct_quest_sort;
import 'quest/quest_x_p.dart' as struct_quest_x_p;

// skill
import 'skill/skill_costs_data.dart' as struct_skill_costs_data;
import 'skill/skill_line.dart' as struct_skill_line;
import 'skill/skill_line_ability.dart' as struct_skill_line_ability;
import 'skill/skill_line_category.dart' as struct_skill_line_category;
import 'skill/skill_race_class_info.dart' as struct_skill_race_class_info;
import 'skill/skill_tiers.dart' as struct_skill_tiers;

// sound
import 'sound/sound_ambience.dart' as struct_sound_ambience;
import 'sound/sound_emitters.dart' as struct_sound_emitters;
import 'sound/sound_entries.dart' as struct_sound_entries;
import 'sound/sound_entries_advanced.dart' as struct_sound_entries_advanced;
import 'sound/sound_filter.dart' as struct_sound_filter;
import 'sound/sound_filter_elem.dart' as struct_sound_filter_elem;
import 'sound/sound_provider_preferences.dart' as struct_sound_provider_preferences;
import 'sound/sound_sample_preferences.dart' as struct_sound_sample_preferences;
import 'sound/sound_water_type.dart' as struct_sound_water_type;

// spell
import 'spell/glyph_properties.dart' as struct_glyph_properties;
import 'spell/glyph_slot.dart' as struct_glyph_slot;
import 'spell/spell.dart' as struct_spell;
import 'spell/spell_cast_times.dart' as struct_spell_cast_times;
import 'spell/spell_category.dart' as struct_spell_category;
import 'spell/spell_chain_effects.dart' as struct_spell_chain_effects;
import 'spell/spell_description_variables.dart' as struct_spell_description_variables;
import 'spell/spell_difficulty.dart' as struct_spell_difficulty;
import 'spell/spell_dispel_type.dart' as struct_spell_dispel_type;
import 'spell/spell_duration.dart' as struct_spell_duration;
import 'spell/spell_effect_camera_shakes.dart' as struct_spell_effect_camera_shakes;
import 'spell/spell_focus_object.dart' as struct_spell_focus_object;
import 'spell/spell_icon.dart' as struct_spell_icon;
import 'spell/spell_item_enchantment.dart' as struct_spell_item_enchantment;
import 'spell/spell_item_enchantment_condition.dart' as struct_spell_item_enchantment_condition;
import 'spell/spell_mechanic.dart' as struct_spell_mechanic;
import 'spell/spell_missile.dart' as struct_spell_missile;
import 'spell/spell_missile_motion.dart' as struct_spell_missile_motion;
import 'spell/spell_radius.dart' as struct_spell_radius;
import 'spell/spell_range.dart' as struct_spell_range;
import 'spell/spell_rune_cost.dart' as struct_spell_rune_cost;
import 'spell/spell_shapeshift_form.dart' as struct_spell_shapeshift_form;
import 'spell/spell_visual.dart' as struct_spell_visual;
import 'spell/spell_visual_effect_name.dart' as struct_spell_visual_effect_name;
import 'spell/spell_visual_kit.dart' as struct_spell_visual_kit;
import 'spell/spell_visual_kit_area_model.dart' as struct_spell_visual_kit_area_model;
import 'spell/spell_visual_kit_model_attach.dart' as struct_spell_visual_kit_model_attach;
import 'spell/spell_visual_precast_transitions.dart' as struct_spell_visual_precast_transitions;
import 'spell/totem_category.dart' as struct_totem_category;

// talent
import 'talent/talent.dart' as struct_talent;
import 'talent/talent_tab.dart' as struct_talent_tab;

// taxi
import 'taxi/taxi_nodes.dart' as struct_taxi_nodes;
import 'taxi/taxi_path.dart' as struct_taxi_path;
import 'taxi/taxi_path_node.dart' as struct_taxi_path_node;

// vehicle
import 'vehicle/vehicle.dart' as struct_vehicle;
import 'vehicle/vehicle_seat.dart' as struct_vehicle_seat;
import 'vehicle/vehicle_u_i_ind_seat.dart' as struct_vehicle_u_i_ind_seat;
import 'vehicle/vehicle_u_i_indicator.dart' as struct_vehicle_u_i_indicator;

class Definitions {
  Definitions._();

  static final achievement = struct_achievement.achievement;
  static final achievementCategory = struct_achievement__category.achievementCategory;
  static final achievementCriteria = struct_achievement__criteria.achievementCriteria;
  static final animationData = struct_animation_data.animationData;
  static final areaGroup = struct_area_group.areaGroup;
  static final areaPOI = struct_area_p_o_i.areaPOI;
  static final areaTable = struct_area_table.areaTable;
  static final areaTrigger = struct_area_trigger.areaTrigger;
  static final attackAnimKits = struct_attack_anim_kits.attackAnimKits;
  static final attackAnimTypes = struct_attack_anim_types.attackAnimTypes;
  static final auctionHouse = struct_auction_house.auctionHouse;
  static final bankBagSlotPrices = struct_bank_bag_slot_prices.bankBagSlotPrices;
  static final bannedAddOns = struct_banned_add_ons.bannedAddOns;
  static final barberShopStyle = struct_barber_shop_style.barberShopStyle;
  static final battlemasterList = struct_battlemaster_list.battlemasterList;
  static final cameraShakes = struct_camera_shakes.cameraShakes;
  static final cfgCategories = struct_cfg__categories.cfgCategories;
  static final cfgConfigs = struct_cfg__configs.cfgConfigs;
  static final charBaseInfo = struct_char_base_info.charBaseInfo;
  static final charHairGeosets = struct_char_hair_geosets.charHairGeosets;
  static final charHairTextures = struct_char_hair_textures.charHairTextures;
  static final charSections = struct_char_sections.charSections;
  static final charStartOutfit = struct_char_start_outfit.charStartOutfit;
  static final charTitles = struct_char_titles.charTitles;
  static final characterFacialHairStyles = struct_character_facial_hair_styles.characterFacialHairStyles;
  static final chatChannels = struct_chat_channels.chatChannels;
  static final chatProfanity = struct_chat_profanity.chatProfanity;
  static final chrClasses = struct_chr_classes.chrClasses;
  static final chrRaces = struct_chr_races.chrRaces;
  static final cinematicCamera = struct_cinematic_camera.cinematicCamera;
  static final cinematicSequences = struct_cinematic_sequences.cinematicSequences;
  static final creatureDisplayInfo = struct_creature_display_info.creatureDisplayInfo;
  static final creatureDisplayInfoExtra = struct_creature_display_info_extra.creatureDisplayInfoExtra;
  static final creatureFamily = struct_creature_family.creatureFamily;
  static final creatureModelData = struct_creature_model_data.creatureModelData;
  static final creatureMovementInfo = struct_creature_movement_info.creatureMovementInfo;
  static final creatureSoundData = struct_creature_sound_data.creatureSoundData;
  static final creatureSpellData = struct_creature_spell_data.creatureSpellData;
  static final creatureType = struct_creature_type.creatureType;
  static final currencyCategory = struct_currency_category.currencyCategory;
  static final currencyTypes = struct_currency_types.currencyTypes;
  static final danceMoves = struct_dance_moves.danceMoves;
  static final deathThudLookups = struct_death_thud_lookups.deathThudLookups;
  static final declinedWord = struct_declined_word.declinedWord;
  static final declinedWordCases = struct_declined_word_cases.declinedWordCases;
  static final destructibleModelData = struct_destructible_model_data.destructibleModelData;
  static final dungeonEncounter = struct_dungeon_encounter.dungeonEncounter;
  static final dungeonMap = struct_dungeon_map.dungeonMap;
  static final dungeonMapChunk = struct_dungeon_map_chunk.dungeonMapChunk;
  static final durabilityCosts = struct_durability_costs.durabilityCosts;
  static final durabilityQuality = struct_durability_quality.durabilityQuality;
  static final emotes = struct_emotes.emotes;
  static final emotesText = struct_emotes_text.emotesText;
  static final emotesTextData = struct_emotes_text_data.emotesTextData;
  static final emotesTextSound = struct_emotes_text_sound.emotesTextSound;
  static final environmentalDamage = struct_environmental_damage.environmentalDamage;
  static final exhaustion = struct_exhaustion.exhaustion;
  static final faction = struct_faction.faction;
  static final factionGroup = struct_faction_group.factionGroup;
  static final factionTemplate = struct_faction_template.factionTemplate;
  static final fileData = struct_file_data.fileData;
  static final footprintTextures = struct_footprint_textures.footprintTextures;
  static final footstepTerrainLookup = struct_footstep_terrain_lookup.footstepTerrainLookup;
  static final gMSurveyAnswers = struct_g_m_survey_answers.gMSurveyAnswers;
  static final gMSurveyCurrentSurvey = struct_g_m_survey_current_survey.gMSurveyCurrentSurvey;
  static final gMSurveyQuestions = struct_g_m_survey_questions.gMSurveyQuestions;
  static final gMSurveySurveys = struct_g_m_survey_surveys.gMSurveySurveys;
  static final gMTicketCategory = struct_g_m_ticket_category.gMTicketCategory;
  static final gameObjectArtKit = struct_game_object_art_kit.gameObjectArtKit;
  static final gameObjectDisplayInfo = struct_game_object_display_info.gameObjectDisplayInfo;
  static final gameTables = struct_game_tables.gameTables;
  static final gameTips = struct_game_tips.gameTips;
  static final gemProperties = struct_gem_properties.gemProperties;
  static final glyphProperties = struct_glyph_properties.glyphProperties;
  static final glyphSlot = struct_glyph_slot.glyphSlot;
  static final groundEffectDoodad = struct_ground_effect_doodad.groundEffectDoodad;
  static final groundEffectTexture = struct_ground_effect_texture.groundEffectTexture;
  static final helmetGeosetVisData = struct_helmet_geoset_vis_data.helmetGeosetVisData;
  static final holidayDescriptions = struct_holiday_descriptions.holidayDescriptions;
  static final holidayNames = struct_holiday_names.holidayNames;
  static final holidays = struct_holidays.holidays;
  static final item = struct_item.item;
  static final itemBagFamily = struct_item_bag_family.itemBagFamily;
  static final itemClass = struct_item_class.itemClass;
  static final itemCondExtCosts = struct_item_cond_ext_costs.itemCondExtCosts;
  static final itemDisplayInfo = struct_item_display_info.itemDisplayInfo;
  static final itemExtendedCost = struct_item_extended_cost.itemExtendedCost;
  static final itemGroupSounds = struct_item_group_sounds.itemGroupSounds;
  static final itemLimitCategory = struct_item_limit_category.itemLimitCategory;
  static final itemPetFood = struct_item_pet_food.itemPetFood;
  static final itemPurchaseGroup = struct_item_purchase_group.itemPurchaseGroup;
  static final itemRandomProperties = struct_item_random_properties.itemRandomProperties;
  static final itemRandomSuffix = struct_item_random_suffix.itemRandomSuffix;
  static final itemSet = struct_item_set.itemSet;
  static final itemSubClass = struct_item_sub_class.itemSubClass;
  static final itemSubClassMask = struct_item_sub_class_mask.itemSubClassMask;
  static final itemVisualEffects = struct_item_visual_effects.itemVisualEffects;
  static final itemVisuals = struct_item_visuals.itemVisuals;
  static final lFGDungeonExpansion = struct_l_f_g_dungeon_expansion.lFGDungeonExpansion;
  static final lFGDungeonGroup = struct_l_f_g_dungeon_group.lFGDungeonGroup;
  static final lFGDungeons = struct_l_f_g_dungeons.lFGDungeons;
  static final languageWords = struct_language_words.languageWords;
  static final languages = struct_languages.languages;
  static final light = struct_light.light;
  static final lightFloatBand = struct_light_float_band.lightFloatBand;
  static final lightIntBand = struct_light_int_band.lightIntBand;
  static final lightParams = struct_light_params.lightParams;
  static final lightSkybox = struct_light_skybox.lightSkybox;
  static final liquidMaterial = struct_liquid_material.liquidMaterial;
  static final liquidType = struct_liquid_type.liquidType;
  static final loadingScreenTaxiSplines = struct_loading_screen_taxi_splines.loadingScreenTaxiSplines;
  static final loadingScreens = struct_loading_screens.loadingScreens;
  static final lock = struct_lock.lock;
  static final lockType = struct_lock_type.lockType;
  static final mailTemplate = struct_mail_template.mailTemplate;
  static final map = struct_map.map;
  static final mapDifficulty = struct_map_difficulty.mapDifficulty;
  static final material = struct_material.material;
  static final movie = struct_movie.movie;
  static final movieFileData = struct_movie_file_data.movieFileData;
  static final movieVariation = struct_movie_variation.movieVariation;
  static final nPCSounds = struct_n_p_c_sounds.nPCSounds;
  static final nameGen = struct_name_gen.nameGen;
  static final namesProfanity = struct_names_profanity.namesProfanity;
  static final namesReserved = struct_names_reserved.namesReserved;
  static final objectEffect = struct_object_effect.objectEffect;
  static final objectEffectGroup = struct_object_effect_group.objectEffectGroup;
  static final objectEffectModifier = struct_object_effect_modifier.objectEffectModifier;
  static final objectEffectPackage = struct_object_effect_package.objectEffectPackage;
  static final objectEffectPackageElem = struct_object_effect_package_elem.objectEffectPackageElem;
  static final overrideSpellData = struct_override_spell_data.overrideSpellData;
  static final package = struct_package.package;
  static final pageTextMaterial = struct_page_text_material.pageTextMaterial;
  static final paperDollItemFrame = struct_paper_doll_item_frame.paperDollItemFrame;
  static final particleColor = struct_particle_color.particleColor;
  static final petPersonality = struct_pet_personality.petPersonality;
  static final petitionType = struct_petition_type.petitionType;
  static final powerDisplay = struct_power_display.powerDisplay;
  static final pvpDifficulty = struct_pvp_difficulty.pvpDifficulty;
  static final questFactionReward = struct_quest_faction_reward.questFactionReward;
  static final questInfo = struct_quest_info.questInfo;
  static final questSort = struct_quest_sort.questSort;
  static final questXP = struct_quest_x_p.questXP;
  static final randPropPoints = struct_rand_prop_points.randPropPoints;
  static final resistances = struct_resistances.resistances;
  static final scalingStatDistribution = struct_scaling_stat_distribution.scalingStatDistribution;
  static final scalingStatValues = struct_scaling_stat_values.scalingStatValues;
  static final screenEffect = struct_screen_effect.screenEffect;
  static final serverMessages = struct_server_messages.serverMessages;
  static final sheatheSoundLookups = struct_sheathe_sound_lookups.sheatheSoundLookups;
  static final skillCostsData = struct_skill_costs_data.skillCostsData;
  static final skillLine = struct_skill_line.skillLine;
  static final skillLineAbility = struct_skill_line_ability.skillLineAbility;
  static final skillLineCategory = struct_skill_line_category.skillLineCategory;
  static final skillRaceClassInfo = struct_skill_race_class_info.skillRaceClassInfo;
  static final skillTiers = struct_skill_tiers.skillTiers;
  static final soundAmbience = struct_sound_ambience.soundAmbience;
  static final soundEmitters = struct_sound_emitters.soundEmitters;
  static final soundEntries = struct_sound_entries.soundEntries;
  static final soundEntriesAdvanced = struct_sound_entries_advanced.soundEntriesAdvanced;
  static final soundFilter = struct_sound_filter.soundFilter;
  static final soundFilterElem = struct_sound_filter_elem.soundFilterElem;
  static final soundProviderPreferences = struct_sound_provider_preferences.soundProviderPreferences;
  static final soundSamplePreferences = struct_sound_sample_preferences.soundSamplePreferences;
  static final soundWaterType = struct_sound_water_type.soundWaterType;
  static final spamMessages = struct_spam_messages.spamMessages;
  static final spell = struct_spell.spell;
  static final spellCastTimes = struct_spell_cast_times.spellCastTimes;
  static final spellCategory = struct_spell_category.spellCategory;
  static final spellChainEffects = struct_spell_chain_effects.spellChainEffects;
  static final spellDescriptionVariables = struct_spell_description_variables.spellDescriptionVariables;
  static final spellDifficulty = struct_spell_difficulty.spellDifficulty;
  static final spellDispelType = struct_spell_dispel_type.spellDispelType;
  static final spellDuration = struct_spell_duration.spellDuration;
  static final spellEffectCameraShakes = struct_spell_effect_camera_shakes.spellEffectCameraShakes;
  static final spellFocusObject = struct_spell_focus_object.spellFocusObject;
  static final spellIcon = struct_spell_icon.spellIcon;
  static final spellItemEnchantment = struct_spell_item_enchantment.spellItemEnchantment;
  static final spellItemEnchantmentCondition = struct_spell_item_enchantment_condition.spellItemEnchantmentCondition;
  static final spellMechanic = struct_spell_mechanic.spellMechanic;
  static final spellMissile = struct_spell_missile.spellMissile;
  static final spellMissileMotion = struct_spell_missile_motion.spellMissileMotion;
  static final spellRadius = struct_spell_radius.spellRadius;
  static final spellRange = struct_spell_range.spellRange;
  static final spellRuneCost = struct_spell_rune_cost.spellRuneCost;
  static final spellShapeshiftForm = struct_spell_shapeshift_form.spellShapeshiftForm;
  static final spellVisual = struct_spell_visual.spellVisual;
  static final spellVisualEffectName = struct_spell_visual_effect_name.spellVisualEffectName;
  static final spellVisualKit = struct_spell_visual_kit.spellVisualKit;
  static final spellVisualKitAreaModel = struct_spell_visual_kit_area_model.spellVisualKitAreaModel;
  static final spellVisualKitModelAttach = struct_spell_visual_kit_model_attach.spellVisualKitModelAttach;
  static final spellVisualPrecastTransitions = struct_spell_visual_precast_transitions.spellVisualPrecastTransitions;
  static final stableSlotPrices = struct_stable_slot_prices.stableSlotPrices;
  static final startupStrings = struct_startup__strings.startupStrings;
  static final stationery = struct_stationery.stationery;
  static final stringLookups = struct_string_lookups.stringLookups;
  static final summonProperties = struct_summon_properties.summonProperties;
  static final talent = struct_talent.talent;
  static final talentTab = struct_talent_tab.talentTab;
  static final taxiNodes = struct_taxi_nodes.taxiNodes;
  static final taxiPath = struct_taxi_path.taxiPath;
  static final taxiPathNode = struct_taxi_path_node.taxiPathNode;
  static final teamContributionPoints = struct_team_contribution_points.teamContributionPoints;
  static final terrainType = struct_terrain_type.terrainType;
  static final terrainTypeSounds = struct_terrain_type_sounds.terrainTypeSounds;
  static final totemCategory = struct_totem_category.totemCategory;
  static final transportAnimation = struct_transport_animation.transportAnimation;
  static final transportPhysics = struct_transport_physics.transportPhysics;
  static final transportRotation = struct_transport_rotation.transportRotation;
  static final uISoundLookups = struct_u_i_sound_lookups.uISoundLookups;
  static final unitBlood = struct_unit_blood.unitBlood;
  static final unitBloodLevels = struct_unit_blood_levels.unitBloodLevels;
  static final vehicle = struct_vehicle.vehicle;
  static final vehicleSeat = struct_vehicle_seat.vehicleSeat;
  static final vehicleUIIndSeat = struct_vehicle_u_i_ind_seat.vehicleUIIndSeat;
  static final vehicleUIIndicator = struct_vehicle_u_i_indicator.vehicleUIIndicator;
  static final videoHardware = struct_video_hardware.videoHardware;
  static final vocalUISounds = struct_vocal_u_i_sounds.vocalUISounds;
  static final wMOAreaTable = struct_w_m_o_area_table.wMOAreaTable;
  static final weaponImpactSounds = struct_weapon_impact_sounds.weaponImpactSounds;
  static final weaponSwingSounds2 = struct_weapon_swing_sounds2.weaponSwingSounds2;
  static final weather = struct_weather.weather;
  static final worldChunkSounds = struct_world_chunk_sounds.worldChunkSounds;
  static final worldMapArea = struct_world_map_area.worldMapArea;
  static final worldMapContinent = struct_world_map_continent.worldMapContinent;
  static final worldMapOverlay = struct_world_map_overlay.worldMapOverlay;
  static final worldMapTransforms = struct_world_map_transforms.worldMapTransforms;
  static final worldSafeLocs = struct_world_safe_locs.worldSafeLocs;
  static final worldStateUI = struct_world_state_u_i.worldStateUI;
  static final worldStateZoneSounds = struct_world_state_zone_sounds.worldStateZoneSounds;
  static final wowErrorStrings = struct_wow_error__strings.wowErrorStrings;
  static final zoneIntroMusicTable = struct_zone_intro_music_table.zoneIntroMusicTable;
  static final zoneMusic = struct_zone_music.zoneMusic;
  static final gtbarberShopCostBase = struct_gtbarber_shop_cost_base.gtbarberShopCostBase;
  static final gtchanceToMeleeCrit = struct_gtchance_to_melee_crit.gtchanceToMeleeCrit;
  static final gtchanceToMeleeCritBase = struct_gtchance_to_melee_crit_base.gtchanceToMeleeCritBase;
  static final gtchanceToSpellCrit = struct_gtchance_to_spell_crit.gtchanceToSpellCrit;
  static final gtchanceToSpellCritBase = struct_gtchance_to_spell_crit_base.gtchanceToSpellCritBase;
  static final gtcombatRatings = struct_gtcombat_ratings.gtcombatRatings;
  static final gtnPCManaCostScaler = struct_gtn_p_c_mana_cost_scaler.gtnPCManaCostScaler;
  static final gtoCTClassCombatRatingScalar = struct_gto_c_t_class_combat_rating_scalar.gtoCTClassCombatRatingScalar;
  static final gtoCTRegenHP = struct_gto_c_t_regen_h_p.gtoCTRegenHP;
  static final gtoCTRegenMP = struct_gto_c_t_regen_m_p.gtoCTRegenMP;
  static final gtregenHPPerSpt = struct_gtregen_h_p_per_spt.gtregenHPPerSpt;
  static final gtregenMPPerSpt = struct_gtregen_m_p_per_spt.gtregenMPPerSpt;
}