const t = require("../../lib/types");

module.exports = {
  ID: t.int32le,
  ContinentID: t.int32le,
  ParentAreaID: t.int32le,
  AreaBit: t.int32le,
  Flags: t.int32le,
  SoundProviderPref: t.int32le,
  SoundProviderPrefUnderwater: t.int32le,
  AmbienceID: t.int32le,
  ZoneMusic: t.int32le,
  IntroSound: t.int32le,
  ExplorationLevel: t.int32le,
  AreaName_Lang_enUS: t.string,
  AreaName_Lang_enGB: t.string,
  AreaName_Lang_deDE: t.string,
  AreaName_Lang_enCN: t.string,
  AreaName_Lang_zhCN: t.string,
  AreaName_Lang_enTW: t.string,
  AreaName_Lang_zhTW: t.string,
  AreaName_Lang_esES: t.string,
  AreaName_Lang_esMX: t.string,
  AreaName_Lang_koKR: t.string,
  AreaName_Lang_frFR: t.string,
  AreaName_Lang_ruRU: t.string,
  AreaName_Lang_ptPT: t.string,
  AreaName_Lang_ptBR: t.string,
  AreaName_Lang_itIT: t.string,
  AreaName_Lang_Unk: t.string,
  AreaName_Lang_Mask: t.int32le,
  FactionGroupMask: t.int32le,
  LiquidTypeID_1: t.int32le,
  LiquidTypeID_2: t.int32le,
  LiquidTypeID_3: t.int32le,
  LiquidTypeID_4: t.int32le,
  MinElevation: t.float32le,
  Ambient_Multiplier: t.float32le,
  Lightid: t.int32le,
};
