const t = require("../../types");

module.exports = {
  id: t.int32le,
  mapId1: t.int32le,
  mapId2: t.int32le,
  mapId3: t.int32le,
  mapId4: t.int32le,
  mapId5: t.int32le,
  mapId6: t.int32le,
  mapId7: t.int32le,
  mapId8: t.int32le,
  instanceType: t.int32le,
  groupAllowed: t.int32le,
  nameLangEnUS: t.string,
  nameLangEnGB: t.string,
  nameLangDeDE: t.string,
  nameLangEnCN: t.string,
  nameLangZhCN: t.string,
  nameLangEnTW: t.string,
  nameLangZhTW: t.string,
  nameLangEsES: t.string,
  nameLangEsMX: t.string,
  nameLangKoKR: t.string,
  nameLangFrFR: t.string,
  nameLangRuRU: t.string,
  nameLangPtPT: t.string,
  nameLangPtBR: t.string,
  nameLangItIT: t.string,
  nameLangUnk: t.string,
  nameLangMask: t.int32le,
  maxGroupSize: t.int32le,
  holidayWorldState: t.int32le,
  minLevel: t.int32le,
  maxLevel: t.int32le,
};
