const t = require("../../types");

module.exports = {
  ID: t.int32le,
  PrecastKit: t.int32le,
  CastKit: t.int32le,
  ImpactKit: t.int32le,
  StateKit: t.int32le,
  StateDoneKit: t.int32le,
  ChannelKit: t.int32le,
  HasMissile: t.int32le,
  MissileModel: t.int32le,
  MissilePathType: t.int32le,
  MissileDestinationAttachment: t.int32le,
  MissileSound: t.int32le,
  AnimEventSoundID: t.int32le,
  Flags: t.int32le,
  CasterImpactKit: t.int32le,
  TargetImpactKit: t.int32le,
  MissileAttachment: t.int32le,
  MissileFollowGroundHeight: t.int32le,
  MissileFollowGroundDropSpeed: t.int32le,
  MissileFollowGroundApproach: t.int32le,
  MissileFollowGroundFlags: t.int32le,
  MissileMotion: t.int32le,
  MissileTargetingKit: t.int32le,
  InstantAreaKit: t.int32le,
  ImpactAreaKit: t.int32le,
  PersistentAreaKit: t.int32le,
  MissileCastOffsetX: t.float32le,
  MissileCastOffsetY: t.float32le,
  MissileCastOffsetZ: t.float32le,
  MissileImpactOffsetX: t.float32le,
  MissileImpactOffsetY: t.float32le,
  MissileImpactOffsetZ: t.float32le,
};
