const t = require("../../types");

module.exports = {
  ID: t.int32le,
  TabID: t.int32le,
  TierID: t.int32le,
  ColumnIndex: t.int32le,
  SpellRank_1: t.int32le,
  SpellRank_2: t.int32le,
  SpellRank_3: t.int32le,
  SpellRank_4: t.int32le,
  SpellRank_5: t.int32le,
  SpellRank_6: t.int32le,
  SpellRank_7: t.int32le,
  SpellRank_8: t.int32le,
  SpellRank_9: t.int32le,
  PrereqTalent_1: t.int32le,
  PrereqTalent_2: t.int32le,
  PrereqTalent_3: t.int32le,
  PrereqRank_1: t.int32le,
  PrereqRank_2: t.int32le,
  PrereqRank_3: t.int32le,
  Flags: t.int32le,
  RequiredSpellID: t.int32le,
  CategoryMask_1: t.int32le,
  CategoryMask_2: t.int32le,
};
