const t = require("../../lib/types");

module.exports = {
  ID: t.int32le,
  Flags: t.int32le,
  TurnSpeed: t.float32le,
  PitchSpeed: t.float32le,
  PitchMin: t.float32le,
  PitchMax: t.float32le,
  SeatID_1: t.int32le,
  SeatID_2: t.int32le,
  SeatID_3: t.int32le,
  SeatID_4: t.int32le,
  SeatID_5: t.int32le,
  SeatID_6: t.int32le,
  SeatID_7: t.int32le,
  SeatID_8: t.int32le,
  MouseLookOffsetPitch: t.float32le,
  CameraFadeDistScalarMin: t.float32le,
  CameraFadeDistScalarMax: t.float32le,
  CameraPitchOffset: t.float32le,
  FacingLimitRight: t.float32le,
  FacingLimitLeft: t.float32le,
  MsslTrgtTurnLingering: t.float32le,
  MsslTrgtPitchLingering: t.float32le,
  MsslTrgtMouseLingering: t.float32le,
  MsslTrgtEndOpacity: t.float32le,
  MsslTrgtArcSpeed: t.float32le,
  MsslTrgtArcRepeat: t.float32le,
  MsslTrgtArcWidth: t.float32le,
  MsslTrgtImpactRadius_1: t.float32le,
  MsslTrgtImpactRadius_2: t.float32le,
  MsslTrgtArcTexture: t.string,
  MsslTrgtImpactTexture: t.string,
  MsslTrgtImpactModel_1: t.string,
  MsslTrgtImpactModel_2: t.string,
  CameraYawOffset: t.float32le,
  UilocomotionType: t.int32le,
  MsslTrgtImpactTexRadius: t.float32le,
  VehicleUIIndicatorID: t.int32le,
  PowerDisplayID_1: t.int32le,
  PowerDisplayID_2: t.int32le,
  PowerDisplayID_3: t.int32le,
};
