import 'package:warcrafty/src/internal/field.dart';
import 'package:warcrafty/src/internal/schema.dart';

/// SpellVisualKit 结构定义
///
/// 基于 WoWDBDefs 定义，版本 3.3.5.12340
const spellVisualKit = DbcSchema(
  name: 'SpellVisualKit',
  format: 'niiiiiiiiiiiiiiiiiiiiffffffffffffffffi',
  fields: [
    Field(index: 0, name: 'ID', description: 'ID', type: FieldType.id),
    Field(index: 1, name: 'StartAnimID', description: 'StartAnimID', type: FieldType.int32),
    Field(index: 2, name: 'AnimID', description: 'AnimID', type: FieldType.int32),
    Field(index: 3, name: 'HeadEffect', description: 'HeadEffect', type: FieldType.int32),
    Field(index: 4, name: 'ChestEffect', description: 'ChestEffect', type: FieldType.int32),
    Field(index: 5, name: 'BaseEffect', description: 'BaseEffect', type: FieldType.int32),
    Field(index: 6, name: 'LeftHandEffect', description: 'LeftHandEffect', type: FieldType.int32),
    Field(index: 7, name: 'RightHandEffect', description: 'RightHandEffect', type: FieldType.int32),
    Field(index: 8, name: 'BreathEffect', description: 'BreathEffect', type: FieldType.int32),
    Field(index: 9, name: 'LeftWeaponEffect', description: 'LeftWeaponEffect', type: FieldType.int32),
    Field(index: 10, name: 'RightWeaponEffect', description: 'RightWeaponEffect', type: FieldType.int32),
    Field(index: 11, name: 'SpecialEffect0', description: 'SpecialEffect 0', type: FieldType.int32),
    Field(index: 12, name: 'SpecialEffect1', description: 'SpecialEffect 1', type: FieldType.int32),
    Field(index: 13, name: 'SpecialEffect2', description: 'SpecialEffect 2', type: FieldType.int32),
    Field(index: 14, name: 'WorldEffect', description: 'WorldEffect', type: FieldType.int32),
    Field(index: 15, name: 'SoundID', description: 'SoundID', type: FieldType.int32),
    Field(index: 16, name: 'ShakeID', description: 'ShakeID', type: FieldType.int32),
    Field(index: 17, name: 'CharProc0', description: 'CharProc 0', type: FieldType.int32),
    Field(index: 18, name: 'CharProc1', description: 'CharProc 1', type: FieldType.int32),
    Field(index: 19, name: 'CharProc2', description: 'CharProc 2', type: FieldType.int32),
    Field(index: 20, name: 'CharProc3', description: 'CharProc 3', type: FieldType.int32),
    Field(index: 21, name: 'CharParamZero0', description: 'CharParamZero 0', type: FieldType.float),
    Field(index: 22, name: 'CharParamZero1', description: 'CharParamZero 1', type: FieldType.float),
    Field(index: 23, name: 'CharParamZero2', description: 'CharParamZero 2', type: FieldType.float),
    Field(index: 24, name: 'CharParamZero3', description: 'CharParamZero 3', type: FieldType.float),
    Field(index: 25, name: 'CharParamOne0', description: 'CharParamOne 0', type: FieldType.float),
    Field(index: 26, name: 'CharParamOne1', description: 'CharParamOne 1', type: FieldType.float),
    Field(index: 27, name: 'CharParamOne2', description: 'CharParamOne 2', type: FieldType.float),
    Field(index: 28, name: 'CharParamOne3', description: 'CharParamOne 3', type: FieldType.float),
    Field(index: 29, name: 'CharParamTwo0', description: 'CharParamTwo 0', type: FieldType.float),
    Field(index: 30, name: 'CharParamTwo1', description: 'CharParamTwo 1', type: FieldType.float),
    Field(index: 31, name: 'CharParamTwo2', description: 'CharParamTwo 2', type: FieldType.float),
    Field(index: 32, name: 'CharParamTwo3', description: 'CharParamTwo 3', type: FieldType.float),
    Field(index: 33, name: 'CharParamThree0', description: 'CharParamThree 0', type: FieldType.float),
    Field(index: 34, name: 'CharParamThree1', description: 'CharParamThree 1', type: FieldType.float),
    Field(index: 35, name: 'CharParamThree2', description: 'CharParamThree 2', type: FieldType.float),
    Field(index: 36, name: 'CharParamThree3', description: 'CharParamThree 3', type: FieldType.float),
    Field(index: 37, name: 'Flags', description: 'Flags', type: FieldType.int32),
  ],
);
