/// Spell.dbc - 法术格式
library;

import '../base/field_definition.dart';
import '../base/structure_definition.dart';
import '../../core/field_format.dart';

/// Spell 格式字符串 (完整版，与 AzerothCore 一致)
const String spellFormat = 'niiiiiiiiiiiixixiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiifxiiiiiiiiiiiiiiiiiiiiiiiiiiiifffiiiiiiiiiiiiiiiiiiiiifffiiiiiiiiiiiiiiifffiiiiiiiiiiiiiissssssssssssssssxssssssssssssssssxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxiiiiiiiiiiixfffxxxiiiiixxfffxx';

/// Spell 结构定义 (主要字段)
const DbcStructureDefinition spell = DbcStructureDefinition(
  name: 'Spell',
  format: spellFormat,
  fields: [
    // 0-11: 基本属性
    FieldDefinition(index: 0, name: 'ID', description: '法术 ID', format: DbcFieldFormat.intType),
    FieldDefinition(index: 1, name: 'Category', description: '类别', format: DbcFieldFormat.intType),
    FieldDefinition(index: 2, name: 'Dispel', description: '驱散类型', format: DbcFieldFormat.intType),
    FieldDefinition(index: 3, name: 'Mechanic', description: '机制', format: DbcFieldFormat.intType),
    FieldDefinition(index: 4, name: 'Attributes', description: '属性', format: DbcFieldFormat.intType),
    FieldDefinition(index: 5, name: 'AttributesEx', description: '扩展属性', format: DbcFieldFormat.intType),
    FieldDefinition(index: 6, name: 'AttributesEx2', description: '扩展属性 2', format: DbcFieldFormat.intType),
    FieldDefinition(index: 7, name: 'AttributesEx3', description: '扩展属性 3', format: DbcFieldFormat.intType),
    FieldDefinition(index: 8, name: 'AttributesEx4', description: '扩展属性 4', format: DbcFieldFormat.intType),
    FieldDefinition(index: 9, name: 'AttributesEx5', description: '扩展属性 5', format: DbcFieldFormat.intType),
    FieldDefinition(index: 10, name: 'AttributesEx6', description: '扩展属性 6', format: DbcFieldFormat.intType),
    FieldDefinition(index: 11, name: 'AttributesEx7', description: '扩展属性 7', format: DbcFieldFormat.intType),
    // 12-27: 姿态相关
    FieldDefinition(index: 12, name: 'Stances', description: '姿态', format: DbcFieldFormat.intType),
    FieldDefinition(index: 13, name: 'Unused13', description: '未使用', format: DbcFieldFormat.na),
    FieldDefinition(index: 14, name: 'StancesNot', description: '排除姿态', format: DbcFieldFormat.intType),
    FieldDefinition(index: 15, name: 'Unused15', description: '未使用', format: DbcFieldFormat.na),
    FieldDefinition(index: 16, name: 'Targets', description: '目标', format: DbcFieldFormat.intType),
    FieldDefinition(index: 17, name: 'TargetCreatureType', description: '目标生物类型', format: DbcFieldFormat.intType),
    FieldDefinition(index: 18, name: 'RequiresSpellFocus', description: '需求法术焦点', format: DbcFieldFormat.intType),
    FieldDefinition(index: 19, name: 'FacingCasterFlags', description: '面向施法者标志', format: DbcFieldFormat.intType),
    FieldDefinition(index: 20, name: 'CasterAuraState', description: '施法者光环状态', format: DbcFieldFormat.intType),
    FieldDefinition(index: 21, name: 'TargetAuraState', description: '目标光环状态', format: DbcFieldFormat.intType),
    FieldDefinition(index: 22, name: 'CasterAuraStateNot', description: '排除施法者光环状态', format: DbcFieldFormat.intType),
    FieldDefinition(index: 23, name: 'TargetAuraStateNot', description: '排除目标光环状态', format: DbcFieldFormat.intType),
    FieldDefinition(index: 24, name: 'CasterAuraSpell', description: '施法者光环法术', format: DbcFieldFormat.intType),
    FieldDefinition(index: 25, name: 'TargetAuraSpell', description: '目标光环法术', format: DbcFieldFormat.intType),
    FieldDefinition(index: 26, name: 'ExcludeCasterAuraSpell', description: '排除施法者光环法术', format: DbcFieldFormat.intType),
    FieldDefinition(index: 27, name: 'ExcludeTargetAuraSpell', description: '排除目标光环法术', format: DbcFieldFormat.intType),
    // 28-35: 时间相关
    FieldDefinition(index: 28, name: 'CastingTimeIndex', description: '施法时间索引', format: DbcFieldFormat.intType),
    FieldDefinition(index: 29, name: 'RecoveryTime', description: '冷却时间', format: DbcFieldFormat.intType),
    FieldDefinition(index: 30, name: 'CategoryRecoveryTime', description: '类别冷却时间', format: DbcFieldFormat.intType),
    FieldDefinition(index: 31, name: 'InterruptFlags', description: '中断标志', format: DbcFieldFormat.intType),
    FieldDefinition(index: 32, name: 'AuraInterruptFlags', description: '光环中断标志', format: DbcFieldFormat.intType),
    FieldDefinition(index: 33, name: 'ChannelInterruptFlags', description: '通道中断标志', format: DbcFieldFormat.intType),
    FieldDefinition(index: 34, name: 'ProcFlags', description: '触发标志', format: DbcFieldFormat.intType),
    FieldDefinition(index: 35, name: 'ProcChance', description: '触发概率', format: DbcFieldFormat.intType),
    // 36-45: 充能与资源
    FieldDefinition(index: 36, name: 'ProcCharges', description: '触发充能', format: DbcFieldFormat.intType),
    FieldDefinition(index: 37, name: 'MaxLevel', description: '最大等级', format: DbcFieldFormat.intType),
    FieldDefinition(index: 38, name: 'BaseLevel', description: '基础等级', format: DbcFieldFormat.intType),
    FieldDefinition(index: 39, name: 'SpellLevel', description: '法术等级', format: DbcFieldFormat.intType),
    FieldDefinition(index: 40, name: 'DurationIndex', description: '持续时间索引', format: DbcFieldFormat.intType),
    FieldDefinition(index: 41, name: 'PowerType', description: '能量类型', format: DbcFieldFormat.intType),
    FieldDefinition(index: 42, name: 'ManaCost', description: '法力消耗', format: DbcFieldFormat.intType),
    FieldDefinition(index: 43, name: 'ManaCostPerLevel', description: '每级法力消耗', format: DbcFieldFormat.intType),
    FieldDefinition(index: 44, name: 'ManaPerSecond', description: '每秒法力', format: DbcFieldFormat.intType),
    FieldDefinition(index: 45, name: 'ManaPerSecondPerLevel', description: '每秒每级法力', format: DbcFieldFormat.intType),
    // 46-50: 范围与速度
    FieldDefinition(index: 46, name: 'RangeIndex', description: '范围索引', format: DbcFieldFormat.intType),
    FieldDefinition(index: 47, name: 'Speed', description: '速度', format: DbcFieldFormat.float),
    FieldDefinition(index: 48, name: 'Unused48', description: '未使用', format: DbcFieldFormat.na),
    FieldDefinition(index: 49, name: 'StackAmount', description: '堆叠数量', format: DbcFieldFormat.intType),
    FieldDefinition(index: 50, name: 'Totem0', description: '图腾 0', format: DbcFieldFormat.intType),
    FieldDefinition(index: 51, name: 'Totem1', description: '图腾 1', format: DbcFieldFormat.intType),
    // 试剂
    FieldDefinition(index: 52, name: 'Reagent0', description: '试剂 0', format: DbcFieldFormat.intType),
    FieldDefinition(index: 53, name: 'Reagent1', description: '试剂 1', format: DbcFieldFormat.intType),
    FieldDefinition(index: 54, name: 'Reagent2', description: '试剂 2', format: DbcFieldFormat.intType),
    FieldDefinition(index: 55, name: 'Reagent3', description: '试剂 3', format: DbcFieldFormat.intType),
    FieldDefinition(index: 56, name: 'Reagent4', description: '试剂 4', format: DbcFieldFormat.intType),
    FieldDefinition(index: 57, name: 'Reagent5', description: '试剂 5', format: DbcFieldFormat.intType),
    FieldDefinition(index: 58, name: 'Reagent6', description: '试剂 6', format: DbcFieldFormat.intType),
    FieldDefinition(index: 59, name: 'Reagent7', description: '试剂 7', format: DbcFieldFormat.intType),
    FieldDefinition(index: 60, name: 'ReagentCount0', description: '试剂数量 0', format: DbcFieldFormat.intType),
    FieldDefinition(index: 61, name: 'ReagentCount1', description: '试剂数量 1', format: DbcFieldFormat.intType),
    FieldDefinition(index: 62, name: 'ReagentCount2', description: '试剂数量 2', format: DbcFieldFormat.intType),
    FieldDefinition(index: 63, name: 'ReagentCount3', description: '试剂数量 3', format: DbcFieldFormat.intType),
    FieldDefinition(index: 64, name: 'ReagentCount4', description: '试剂数量 4', format: DbcFieldFormat.intType),
    FieldDefinition(index: 65, name: 'ReagentCount5', description: '试剂数量 5', format: DbcFieldFormat.intType),
    FieldDefinition(index: 66, name: 'ReagentCount6', description: '试剂数量 6', format: DbcFieldFormat.intType),
    FieldDefinition(index: 67, name: 'ReagentCount7', description: '试剂数量 7', format: DbcFieldFormat.intType),
    // 68-70: 物品需求
    FieldDefinition(index: 68, name: 'EquippedItemClass', description: '需求物品类别', format: DbcFieldFormat.intType),
    FieldDefinition(index: 69, name: 'EquippedItemSubClassMask', description: '需求物品子类别掩码', format: DbcFieldFormat.intType),
    FieldDefinition(index: 70, name: 'EquippedItemInventoryTypeMask', description: '需求物品背包类型掩码', format: DbcFieldFormat.intType),
    // 效果 (71-130)
    FieldDefinition(index: 71, name: 'Effect0', description: '效果 0', format: DbcFieldFormat.intType),
    FieldDefinition(index: 72, name: 'Effect1', description: '效果 1', format: DbcFieldFormat.intType),
    FieldDefinition(index: 73, name: 'Effect2', description: '效果 2', format: DbcFieldFormat.intType),
    // ... 更多效果字段省略
    FieldDefinition(index: 136, name: 'SpellName_enUS', description: '英文法术名称', format: DbcFieldFormat.string),
    FieldDefinition(index: 137, name: 'SpellName_enGB', description: '英式英文法术名称', format: DbcFieldFormat.string),
    FieldDefinition(index: 138, name: 'SpellName_koKR', description: '韩文法术名称', format: DbcFieldFormat.string),
    FieldDefinition(index: 139, name: 'SpellName_frFR', description: '法文法术名称', format: DbcFieldFormat.string),
    FieldDefinition(index: 140, name: 'SpellName_deDE', description: '德文法术名称', format: DbcFieldFormat.string),
    FieldDefinition(index: 141, name: 'SpellName_enCN', description: '简体中文法术名称', format: DbcFieldFormat.string),
    FieldDefinition(index: 142, name: 'SpellName_zhCN', description: '繁体中文法术名称', format: DbcFieldFormat.string),
    FieldDefinition(index: 143, name: 'SpellName_zhTW', description: '台湾繁体中文法术名称', format: DbcFieldFormat.string),
    FieldDefinition(index: 144, name: 'SpellName_esES', description: '西班牙文法术名称', format: DbcFieldFormat.string),
    FieldDefinition(index: 145, name: 'SpellName_esMX', description: '墨西哥西班牙文法术名称', format: DbcFieldFormat.string),
    FieldDefinition(index: 146, name: 'SpellName_ruRU', description: '俄文法术名称', format: DbcFieldFormat.string),
    FieldDefinition(index: 147, name: 'SpellName_ptBR', description: '葡萄牙文法术名称', format: DbcFieldFormat.string),
    FieldDefinition(index: 148, name: 'SpellName_itIT', description: '意大利文法术名称', format: DbcFieldFormat.string),
    FieldDefinition(index: 149, name: 'SpellName_ptPT', description: '葡萄牙葡萄牙文法术名称', format: DbcFieldFormat.string),
    FieldDefinition(index: 150, name: 'SpellName_unk', description: '未知语言法术名称', format: DbcFieldFormat.string),
    FieldDefinition(index: 151, name: 'SpellName_unk2', description: '未知语言法术名称 2', format: DbcFieldFormat.string),
    FieldDefinition(index: 152, name: 'Rank_enUS', description: '英文等级', format: DbcFieldFormat.string),
    FieldDefinition(index: 153, name: 'Rank_enGB', description: '英式英文等级', format: DbcFieldFormat.string),
    FieldDefinition(index: 154, name: 'Rank_koKR', description: '韩文等级', format: DbcFieldFormat.string),
    FieldDefinition(index: 155, name: 'Rank_frFR', description: '法文等级', format: DbcFieldFormat.string),
    FieldDefinition(index: 156, name: 'Rank_deDE', description: '德文等级', format: DbcFieldFormat.string),
    FieldDefinition(index: 157, name: 'Rank_enCN', description: '简体中文等级', format: DbcFieldFormat.string),
    FieldDefinition(index: 158, name: 'Rank_zhCN', description: '繁体中文等级', format: DbcFieldFormat.string),
    FieldDefinition(index: 159, name: 'Rank_zhTW', description: '台湾繁体中文等级', format: DbcFieldFormat.string),
    FieldDefinition(index: 160, name: 'Rank_esES', description: '西班牙文等级', format: DbcFieldFormat.string),
    FieldDefinition(index: 161, name: 'Rank_esMX', description: '墨西哥西班牙文等级', format: DbcFieldFormat.string),
    FieldDefinition(index: 162, name: 'Rank_ruRU', description: '俄文等级', format: DbcFieldFormat.string),
    FieldDefinition(index: 163, name: 'Rank_ptBR', description: '葡萄牙文等级', format: DbcFieldFormat.string),
    FieldDefinition(index: 164, name: 'Rank_itIT', description: '意大利文等级', format: DbcFieldFormat.string),
    FieldDefinition(index: 165, name: 'Rank_ptPT', description: '葡萄牙葡萄牙文等级', format: DbcFieldFormat.string),
    FieldDefinition(index: 166, name: 'Rank_unk', description: '未知语言等级', format: DbcFieldFormat.string),
    FieldDefinition(index: 167, name: 'Rank_unk2', description: '未知语言等级 2', format: DbcFieldFormat.string),
    // ... 后续字段省略
  ],
);
