import 'package:warcrafty/src/schema/field.dart';
import 'package:warcrafty/src/schema/schema.dart';
import 'package:warcrafty/src/tools/locale_fields.dart';

/// Spell 结构定义
///
/// 基于 WoWDBDefs 定义，版本 3.3.5.12340
final spell = DbcSchema(
  name: 'Spell',
  format: 'niiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiifiiiiiiiiiiiiiiiiiiiiiiiiiiiiifffiiiiiiiiiiiiiiiiiiiiifffiiiiiiiiiiiiiiifffiiiiiiiiiiiiiissssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssiiiiiiiiiiiifffiiiiiiiiiifffii',
  fields: [
    const Field(index: 0, name: 'ID', description: 'ID', type: FieldType.id),
    const Field(index: 1, name: 'Category', description: 'Category', type: FieldType.int32),
    const Field(index: 2, name: 'DispelType', description: 'DispelType', type: FieldType.int32),
    const Field(index: 3, name: 'Mechanic', description: 'Mechanic', type: FieldType.int32),
    const Field(index: 4, name: 'Attributes', description: 'Attributes', type: FieldType.int32),
    const Field(index: 5, name: 'AttributesEx', description: 'AttributesEx', type: FieldType.int32),
    const Field(index: 6, name: 'AttributesExB', description: 'AttributesExB', type: FieldType.int32),
    const Field(index: 7, name: 'AttributesExC', description: 'AttributesExC', type: FieldType.int32),
    const Field(index: 8, name: 'AttributesExD', description: 'AttributesExD', type: FieldType.int32),
    const Field(index: 9, name: 'AttributesExE', description: 'AttributesExE', type: FieldType.int32),
    const Field(index: 10, name: 'AttributesExF', description: 'AttributesExF', type: FieldType.int32),
    const Field(index: 11, name: 'AttributesExG', description: 'AttributesExG', type: FieldType.int32),
    const Field(index: 12, name: 'ShapeshiftMask0', description: 'ShapeshiftMask 0', type: FieldType.int32),
    const Field(index: 13, name: 'ShapeshiftMask1', description: 'ShapeshiftMask 1', type: FieldType.int32),
    const Field(index: 14, name: 'ShapeshiftExclude0', description: 'ShapeshiftExclude 0', type: FieldType.int32),
    const Field(index: 15, name: 'ShapeshiftExclude1', description: 'ShapeshiftExclude 1', type: FieldType.int32),
    const Field(index: 16, name: 'Targets', description: 'Targets', type: FieldType.int32),
    const Field(index: 17, name: 'TargetCreatureType', description: 'TargetCreatureType', type: FieldType.int32),
    const Field(index: 18, name: 'RequiresSpellFocus', description: 'RequiresSpellFocus', type: FieldType.int32),
    const Field(index: 19, name: 'FacingCasterFlags', description: 'FacingCasterFlags', type: FieldType.int32),
    const Field(index: 20, name: 'CasterAuraState', description: 'CasterAuraState', type: FieldType.int32),
    const Field(index: 21, name: 'TargetAuraState', description: 'TargetAuraState', type: FieldType.int32),
    const Field(index: 22, name: 'ExcludeCasterAuraState', description: 'ExcludeCasterAuraState', type: FieldType.int32),
    const Field(index: 23, name: 'ExcludeTargetAuraState', description: 'ExcludeTargetAuraState', type: FieldType.int32),
    const Field(index: 24, name: 'CasterAuraSpell', description: 'CasterAuraSpell', type: FieldType.int32),
    const Field(index: 25, name: 'TargetAuraSpell', description: 'TargetAuraSpell', type: FieldType.int32),
    const Field(index: 26, name: 'ExcludeCasterAuraSpell', description: 'ExcludeCasterAuraSpell', type: FieldType.int32),
    const Field(index: 27, name: 'ExcludeTargetAuraSpell', description: 'ExcludeTargetAuraSpell', type: FieldType.int32),
    const Field(index: 28, name: 'CastingTimeIndex', description: 'CastingTimeIndex', type: FieldType.int32),
    const Field(index: 29, name: 'RecoveryTime', description: 'RecoveryTime', type: FieldType.int32),
    const Field(index: 30, name: 'CategoryRecoveryTime', description: 'CategoryRecoveryTime', type: FieldType.int32),
    const Field(index: 31, name: 'InterruptFlags', description: 'InterruptFlags', type: FieldType.int32),
    const Field(index: 32, name: 'AuraInterruptFlags', description: 'AuraInterruptFlags', type: FieldType.int32),
    const Field(index: 33, name: 'ChannelInterruptFlags', description: 'ChannelInterruptFlags', type: FieldType.int32),
    const Field(index: 34, name: 'ProcTypeMask', description: 'ProcTypeMask', type: FieldType.int32),
    const Field(index: 35, name: 'ProcChance', description: 'ProcChance', type: FieldType.int32),
    const Field(index: 36, name: 'ProcCharges', description: 'ProcCharges', type: FieldType.int32),
    const Field(index: 37, name: 'MaxLevel', description: 'MaxLevel', type: FieldType.int32),
    const Field(index: 38, name: 'BaseLevel', description: 'BaseLevel', type: FieldType.int32),
    const Field(index: 39, name: 'SpellLevel', description: 'SpellLevel', type: FieldType.int32),
    const Field(index: 40, name: 'DurationIndex', description: 'DurationIndex', type: FieldType.int32),
    const Field(index: 41, name: 'PowerType', description: 'PowerType', type: FieldType.int32),
    const Field(index: 42, name: 'ManaCost', description: 'ManaCost', type: FieldType.int32),
    const Field(index: 43, name: 'ManaCostPerLevel', description: 'ManaCostPerLevel', type: FieldType.int32),
    const Field(index: 44, name: 'ManaPerSecond', description: 'ManaPerSecond', type: FieldType.int32),
    const Field(index: 45, name: 'ManaPerSecondPerLevel', description: 'ManaPerSecondPerLevel', type: FieldType.int32),
    const Field(index: 46, name: 'RangeIndex', description: 'RangeIndex', type: FieldType.int32),
    const Field(index: 47, name: 'Speed', description: 'Speed', type: FieldType.float),
    const Field(index: 48, name: 'ModalNextSpell', description: 'ModalNextSpell', type: FieldType.int32),
    const Field(index: 49, name: 'CumulativeAura', description: 'CumulativeAura', type: FieldType.int32),
    const Field(index: 50, name: 'Totem0', description: 'Totem 0', type: FieldType.int32),
    const Field(index: 51, name: 'Totem1', description: 'Totem 1', type: FieldType.int32),
    const Field(index: 52, name: 'Reagent0', description: 'Reagent 0', type: FieldType.int32),
    const Field(index: 53, name: 'Reagent1', description: 'Reagent 1', type: FieldType.int32),
    const Field(index: 54, name: 'Reagent2', description: 'Reagent 2', type: FieldType.int32),
    const Field(index: 55, name: 'Reagent3', description: 'Reagent 3', type: FieldType.int32),
    const Field(index: 56, name: 'Reagent4', description: 'Reagent 4', type: FieldType.int32),
    const Field(index: 57, name: 'Reagent5', description: 'Reagent 5', type: FieldType.int32),
    const Field(index: 58, name: 'Reagent6', description: 'Reagent 6', type: FieldType.int32),
    const Field(index: 59, name: 'Reagent7', description: 'Reagent 7', type: FieldType.int32),
    const Field(index: 60, name: 'ReagentCount0', description: 'ReagentCount 0', type: FieldType.int32),
    const Field(index: 61, name: 'ReagentCount1', description: 'ReagentCount 1', type: FieldType.int32),
    const Field(index: 62, name: 'ReagentCount2', description: 'ReagentCount 2', type: FieldType.int32),
    const Field(index: 63, name: 'ReagentCount3', description: 'ReagentCount 3', type: FieldType.int32),
    const Field(index: 64, name: 'ReagentCount4', description: 'ReagentCount 4', type: FieldType.int32),
    const Field(index: 65, name: 'ReagentCount5', description: 'ReagentCount 5', type: FieldType.int32),
    const Field(index: 66, name: 'ReagentCount6', description: 'ReagentCount 6', type: FieldType.int32),
    const Field(index: 67, name: 'ReagentCount7', description: 'ReagentCount 7', type: FieldType.int32),
    const Field(index: 68, name: 'EquippedItemClass', description: 'EquippedItemClass', type: FieldType.int32),
    const Field(index: 69, name: 'EquippedItemSubclass', description: 'EquippedItemSubclass', type: FieldType.int32),
    const Field(index: 70, name: 'EquippedItemInvTypes', description: 'EquippedItemInvTypes', type: FieldType.int32),
    const Field(index: 71, name: 'Effect0', description: 'Effect 0', type: FieldType.int32),
    const Field(index: 72, name: 'Effect1', description: 'Effect 1', type: FieldType.int32),
    const Field(index: 73, name: 'Effect2', description: 'Effect 2', type: FieldType.int32),
    const Field(index: 74, name: 'EffectDieSides0', description: 'EffectDieSides 0', type: FieldType.int32),
    const Field(index: 75, name: 'EffectDieSides1', description: 'EffectDieSides 1', type: FieldType.int32),
    const Field(index: 76, name: 'EffectDieSides2', description: 'EffectDieSides 2', type: FieldType.int32),
    const Field(index: 77, name: 'EffectRealPointsPerLevel0', description: 'EffectRealPointsPerLevel 0', type: FieldType.float),
    const Field(index: 78, name: 'EffectRealPointsPerLevel1', description: 'EffectRealPointsPerLevel 1', type: FieldType.float),
    const Field(index: 79, name: 'EffectRealPointsPerLevel2', description: 'EffectRealPointsPerLevel 2', type: FieldType.float),
    const Field(index: 80, name: 'EffectBasePoints0', description: 'EffectBasePoints 0', type: FieldType.int32),
    const Field(index: 81, name: 'EffectBasePoints1', description: 'EffectBasePoints 1', type: FieldType.int32),
    const Field(index: 82, name: 'EffectBasePoints2', description: 'EffectBasePoints 2', type: FieldType.int32),
    const Field(index: 83, name: 'EffectMechanic0', description: 'EffectMechanic 0', type: FieldType.int32),
    const Field(index: 84, name: 'EffectMechanic1', description: 'EffectMechanic 1', type: FieldType.int32),
    const Field(index: 85, name: 'EffectMechanic2', description: 'EffectMechanic 2', type: FieldType.int32),
    const Field(index: 86, name: 'ImplicitTargetA0', description: 'ImplicitTargetA 0', type: FieldType.int32),
    const Field(index: 87, name: 'ImplicitTargetA1', description: 'ImplicitTargetA 1', type: FieldType.int32),
    const Field(index: 88, name: 'ImplicitTargetA2', description: 'ImplicitTargetA 2', type: FieldType.int32),
    const Field(index: 89, name: 'ImplicitTargetB0', description: 'ImplicitTargetB 0', type: FieldType.int32),
    const Field(index: 90, name: 'ImplicitTargetB1', description: 'ImplicitTargetB 1', type: FieldType.int32),
    const Field(index: 91, name: 'ImplicitTargetB2', description: 'ImplicitTargetB 2', type: FieldType.int32),
    const Field(index: 92, name: 'EffectRadiusIndex0', description: 'EffectRadiusIndex 0', type: FieldType.int32),
    const Field(index: 93, name: 'EffectRadiusIndex1', description: 'EffectRadiusIndex 1', type: FieldType.int32),
    const Field(index: 94, name: 'EffectRadiusIndex2', description: 'EffectRadiusIndex 2', type: FieldType.int32),
    const Field(index: 95, name: 'EffectAura0', description: 'EffectAura 0', type: FieldType.int32),
    const Field(index: 96, name: 'EffectAura1', description: 'EffectAura 1', type: FieldType.int32),
    const Field(index: 97, name: 'EffectAura2', description: 'EffectAura 2', type: FieldType.int32),
    const Field(index: 98, name: 'EffectAuraPeriod0', description: 'EffectAuraPeriod 0', type: FieldType.int32),
    const Field(index: 99, name: 'EffectAuraPeriod1', description: 'EffectAuraPeriod 1', type: FieldType.int32),
    const Field(index: 100, name: 'EffectAuraPeriod2', description: 'EffectAuraPeriod 2', type: FieldType.int32),
    const Field(index: 101, name: 'EffectAmplitude0', description: 'EffectAmplitude 0', type: FieldType.float),
    const Field(index: 102, name: 'EffectAmplitude1', description: 'EffectAmplitude 1', type: FieldType.float),
    const Field(index: 103, name: 'EffectAmplitude2', description: 'EffectAmplitude 2', type: FieldType.float),
    const Field(index: 104, name: 'EffectChainTargets0', description: 'EffectChainTargets 0', type: FieldType.int32),
    const Field(index: 105, name: 'EffectChainTargets1', description: 'EffectChainTargets 1', type: FieldType.int32),
    const Field(index: 106, name: 'EffectChainTargets2', description: 'EffectChainTargets 2', type: FieldType.int32),
    const Field(index: 107, name: 'EffectItemType0', description: 'EffectItemType 0', type: FieldType.int32),
    const Field(index: 108, name: 'EffectItemType1', description: 'EffectItemType 1', type: FieldType.int32),
    const Field(index: 109, name: 'EffectItemType2', description: 'EffectItemType 2', type: FieldType.int32),
    const Field(index: 110, name: 'EffectMiscValue0', description: 'EffectMiscValue 0', type: FieldType.int32),
    const Field(index: 111, name: 'EffectMiscValue1', description: 'EffectMiscValue 1', type: FieldType.int32),
    const Field(index: 112, name: 'EffectMiscValue2', description: 'EffectMiscValue 2', type: FieldType.int32),
    const Field(index: 113, name: 'EffectMiscValueB0', description: 'EffectMiscValueB 0', type: FieldType.int32),
    const Field(index: 114, name: 'EffectMiscValueB1', description: 'EffectMiscValueB 1', type: FieldType.int32),
    const Field(index: 115, name: 'EffectMiscValueB2', description: 'EffectMiscValueB 2', type: FieldType.int32),
    const Field(index: 116, name: 'EffectTriggerSpell0', description: 'EffectTriggerSpell 0', type: FieldType.int32),
    const Field(index: 117, name: 'EffectTriggerSpell1', description: 'EffectTriggerSpell 1', type: FieldType.int32),
    const Field(index: 118, name: 'EffectTriggerSpell2', description: 'EffectTriggerSpell 2', type: FieldType.int32),
    const Field(index: 119, name: 'EffectPointsPerCombo0', description: 'EffectPointsPerCombo 0', type: FieldType.float),
    const Field(index: 120, name: 'EffectPointsPerCombo1', description: 'EffectPointsPerCombo 1', type: FieldType.float),
    const Field(index: 121, name: 'EffectPointsPerCombo2', description: 'EffectPointsPerCombo 2', type: FieldType.float),
    const Field(index: 122, name: 'EffectSpellClassMaskA0', description: 'EffectSpellClassMaskA 0', type: FieldType.int32),
    const Field(index: 123, name: 'EffectSpellClassMaskA1', description: 'EffectSpellClassMaskA 1', type: FieldType.int32),
    const Field(index: 124, name: 'EffectSpellClassMaskA2', description: 'EffectSpellClassMaskA 2', type: FieldType.int32),
    const Field(index: 125, name: 'EffectSpellClassMaskB0', description: 'EffectSpellClassMaskB 0', type: FieldType.int32),
    const Field(index: 126, name: 'EffectSpellClassMaskB1', description: 'EffectSpellClassMaskB 1', type: FieldType.int32),
    const Field(index: 127, name: 'EffectSpellClassMaskB2', description: 'EffectSpellClassMaskB 2', type: FieldType.int32),
    const Field(index: 128, name: 'EffectSpellClassMaskC0', description: 'EffectSpellClassMaskC 0', type: FieldType.int32),
    const Field(index: 129, name: 'EffectSpellClassMaskC1', description: 'EffectSpellClassMaskC 1', type: FieldType.int32),
    const Field(index: 130, name: 'EffectSpellClassMaskC2', description: 'EffectSpellClassMaskC 2', type: FieldType.int32),
    const Field(index: 131, name: 'SpellVisualID0', description: 'SpellVisualID 0', type: FieldType.int32),
    const Field(index: 132, name: 'SpellVisualID1', description: 'SpellVisualID 1', type: FieldType.int32),
    const Field(index: 133, name: 'SpellIconID', description: 'SpellIconID', type: FieldType.int32),
    const Field(index: 134, name: 'ActiveIconID', description: 'ActiveIconID', type: FieldType.int32),
    const Field(index: 135, name: 'SpellPriority', description: 'SpellPriority', type: FieldType.int32),
    ...createLocaleFieldsWithFlag(136, 'Name_lang', 'Name_lang'),
    ...createLocaleFieldsWithFlag(153, 'NameSubtext_lang', 'NameSubtext_lang'),
    ...createLocaleFieldsWithFlag(170, 'Description_lang', 'Description_lang'),
    ...createLocaleFieldsWithFlag(187, 'AuraDescription_lang', 'AuraDescription_lang'),
    const Field(index: 204, name: 'ManaCostPct', description: 'ManaCostPct', type: FieldType.int32),
    const Field(index: 205, name: 'StartRecoveryCategory', description: 'StartRecoveryCategory', type: FieldType.int32),
    const Field(index: 206, name: 'StartRecoveryTime', description: 'StartRecoveryTime', type: FieldType.int32),
    const Field(index: 207, name: 'MaxTargetLevel', description: 'MaxTargetLevel', type: FieldType.int32),
    const Field(index: 208, name: 'SpellClassSet', description: 'SpellClassSet', type: FieldType.int32),
    const Field(index: 209, name: 'SpellClassMask0', description: 'SpellClassMask 0', type: FieldType.int32),
    const Field(index: 210, name: 'SpellClassMask1', description: 'SpellClassMask 1', type: FieldType.int32),
    const Field(index: 211, name: 'SpellClassMask2', description: 'SpellClassMask 2', type: FieldType.int32),
    const Field(index: 212, name: 'MaxTargets', description: 'MaxTargets', type: FieldType.int32),
    const Field(index: 213, name: 'DefenseType', description: 'DefenseType', type: FieldType.int32),
    const Field(index: 214, name: 'PreventionType', description: 'PreventionType', type: FieldType.int32),
    const Field(index: 215, name: 'StanceBarOrder', description: 'StanceBarOrder', type: FieldType.int32),
    const Field(index: 216, name: 'EffectChainAmplitude0', description: 'EffectChainAmplitude 0', type: FieldType.float),
    const Field(index: 217, name: 'EffectChainAmplitude1', description: 'EffectChainAmplitude 1', type: FieldType.float),
    const Field(index: 218, name: 'EffectChainAmplitude2', description: 'EffectChainAmplitude 2', type: FieldType.float),
    const Field(index: 219, name: 'MinFactionID', description: 'MinFactionID', type: FieldType.int32),
    const Field(index: 220, name: 'MinReputation', description: 'MinReputation', type: FieldType.int32),
    const Field(index: 221, name: 'RequiredAuraVision', description: 'RequiredAuraVision', type: FieldType.int32),
    const Field(index: 222, name: 'RequiredTotemCategoryID0', description: 'RequiredTotemCategoryID 0', type: FieldType.int32),
    const Field(index: 223, name: 'RequiredTotemCategoryID1', description: 'RequiredTotemCategoryID 1', type: FieldType.int32),
    const Field(index: 224, name: 'RequiredAreasID', description: 'RequiredAreasID', type: FieldType.int32),
    const Field(index: 225, name: 'SchoolMask', description: 'SchoolMask', type: FieldType.int32),
    const Field(index: 226, name: 'RuneCostID', description: 'RuneCostID', type: FieldType.int32),
    const Field(index: 227, name: 'SpellMissileID', description: 'SpellMissileID', type: FieldType.int32),
    const Field(index: 228, name: 'PowerDisplayID', description: 'PowerDisplayID', type: FieldType.int32),
    const Field(index: 229, name: 'EffectBonusCoefficient0', description: 'EffectBonusCoefficient 0', type: FieldType.float),
    const Field(index: 230, name: 'EffectBonusCoefficient1', description: 'EffectBonusCoefficient 1', type: FieldType.float),
    const Field(index: 231, name: 'EffectBonusCoefficient2', description: 'EffectBonusCoefficient 2', type: FieldType.float),
    const Field(index: 232, name: 'DescriptionVariablesID', description: 'DescriptionVariablesID', type: FieldType.int32),
    const Field(index: 233, name: 'Difficulty', description: 'Difficulty', type: FieldType.int32),
  ],
);
