import 'package:warcrafty/src/core/field_definition.dart';
import 'package:warcrafty/src/core/structure_definition.dart';
import 'package:warcrafty/src/core/field_format.dart';
import 'package:warcrafty/src/core/locale_fields.dart';

/// Spell 结构定义
///
/// 基于 WoWDBDefs 定义，版本 3.3.5.12340
final spell = DbcStructureDefinition(
  name: 'Spell',
  format: 'niiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiifiiiiiiiiiiiiiiiiiiiiiiiiiiiiifffiiiiiiiiiiiiiiiiiiiiifffiiiiiiiiiiiiiiifffiiiiiiiiiiiiiissssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssiiiiiiiiiiiifffiiiiiiiiiifffii',
  fields: [
    const FieldDefinition(index: 0, name: 'ID', description: 'ID', format: DbcFieldFormat.indexField),
    const FieldDefinition(index: 1, name: 'Category', description: 'Category', format: DbcFieldFormat.intType),
    const FieldDefinition(index: 2, name: 'DispelType', description: 'DispelType', format: DbcFieldFormat.intType),
    const FieldDefinition(index: 3, name: 'Mechanic', description: 'Mechanic', format: DbcFieldFormat.intType),
    const FieldDefinition(index: 4, name: 'Attributes', description: 'Attributes', format: DbcFieldFormat.intType),
    const FieldDefinition(index: 5, name: 'AttributesEx', description: 'AttributesEx', format: DbcFieldFormat.intType),
    const FieldDefinition(index: 6, name: 'AttributesExB', description: 'AttributesExB', format: DbcFieldFormat.intType),
    const FieldDefinition(index: 7, name: 'AttributesExC', description: 'AttributesExC', format: DbcFieldFormat.intType),
    const FieldDefinition(index: 8, name: 'AttributesExD', description: 'AttributesExD', format: DbcFieldFormat.intType),
    const FieldDefinition(index: 9, name: 'AttributesExE', description: 'AttributesExE', format: DbcFieldFormat.intType),
    const FieldDefinition(index: 10, name: 'AttributesExF', description: 'AttributesExF', format: DbcFieldFormat.intType),
    const FieldDefinition(index: 11, name: 'AttributesExG', description: 'AttributesExG', format: DbcFieldFormat.intType),
    const FieldDefinition(index: 12, name: 'ShapeshiftMask0', description: 'ShapeshiftMask 0', format: DbcFieldFormat.intType),
    const FieldDefinition(index: 13, name: 'ShapeshiftMask1', description: 'ShapeshiftMask 1', format: DbcFieldFormat.intType),
    const FieldDefinition(index: 14, name: 'ShapeshiftExclude0', description: 'ShapeshiftExclude 0', format: DbcFieldFormat.intType),
    const FieldDefinition(index: 15, name: 'ShapeshiftExclude1', description: 'ShapeshiftExclude 1', format: DbcFieldFormat.intType),
    const FieldDefinition(index: 16, name: 'Targets', description: 'Targets', format: DbcFieldFormat.intType),
    const FieldDefinition(index: 17, name: 'TargetCreatureType', description: 'TargetCreatureType', format: DbcFieldFormat.intType),
    const FieldDefinition(index: 18, name: 'RequiresSpellFocus', description: 'RequiresSpellFocus', format: DbcFieldFormat.intType),
    const FieldDefinition(index: 19, name: 'FacingCasterFlags', description: 'FacingCasterFlags', format: DbcFieldFormat.intType),
    const FieldDefinition(index: 20, name: 'CasterAuraState', description: 'CasterAuraState', format: DbcFieldFormat.intType),
    const FieldDefinition(index: 21, name: 'TargetAuraState', description: 'TargetAuraState', format: DbcFieldFormat.intType),
    const FieldDefinition(index: 22, name: 'ExcludeCasterAuraState', description: 'ExcludeCasterAuraState', format: DbcFieldFormat.intType),
    const FieldDefinition(index: 23, name: 'ExcludeTargetAuraState', description: 'ExcludeTargetAuraState', format: DbcFieldFormat.intType),
    const FieldDefinition(index: 24, name: 'CasterAuraSpell', description: 'CasterAuraSpell', format: DbcFieldFormat.intType),
    const FieldDefinition(index: 25, name: 'TargetAuraSpell', description: 'TargetAuraSpell', format: DbcFieldFormat.intType),
    const FieldDefinition(index: 26, name: 'ExcludeCasterAuraSpell', description: 'ExcludeCasterAuraSpell', format: DbcFieldFormat.intType),
    const FieldDefinition(index: 27, name: 'ExcludeTargetAuraSpell', description: 'ExcludeTargetAuraSpell', format: DbcFieldFormat.intType),
    const FieldDefinition(index: 28, name: 'CastingTimeIndex', description: 'CastingTimeIndex', format: DbcFieldFormat.intType),
    const FieldDefinition(index: 29, name: 'RecoveryTime', description: 'RecoveryTime', format: DbcFieldFormat.intType),
    const FieldDefinition(index: 30, name: 'CategoryRecoveryTime', description: 'CategoryRecoveryTime', format: DbcFieldFormat.intType),
    const FieldDefinition(index: 31, name: 'InterruptFlags', description: 'InterruptFlags', format: DbcFieldFormat.intType),
    const FieldDefinition(index: 32, name: 'AuraInterruptFlags', description: 'AuraInterruptFlags', format: DbcFieldFormat.intType),
    const FieldDefinition(index: 33, name: 'ChannelInterruptFlags', description: 'ChannelInterruptFlags', format: DbcFieldFormat.intType),
    const FieldDefinition(index: 34, name: 'ProcTypeMask', description: 'ProcTypeMask', format: DbcFieldFormat.intType),
    const FieldDefinition(index: 35, name: 'ProcChance', description: 'ProcChance', format: DbcFieldFormat.intType),
    const FieldDefinition(index: 36, name: 'ProcCharges', description: 'ProcCharges', format: DbcFieldFormat.intType),
    const FieldDefinition(index: 37, name: 'MaxLevel', description: 'MaxLevel', format: DbcFieldFormat.intType),
    const FieldDefinition(index: 38, name: 'BaseLevel', description: 'BaseLevel', format: DbcFieldFormat.intType),
    const FieldDefinition(index: 39, name: 'SpellLevel', description: 'SpellLevel', format: DbcFieldFormat.intType),
    const FieldDefinition(index: 40, name: 'DurationIndex', description: 'DurationIndex', format: DbcFieldFormat.intType),
    const FieldDefinition(index: 41, name: 'PowerType', description: 'PowerType', format: DbcFieldFormat.intType),
    const FieldDefinition(index: 42, name: 'ManaCost', description: 'ManaCost', format: DbcFieldFormat.intType),
    const FieldDefinition(index: 43, name: 'ManaCostPerLevel', description: 'ManaCostPerLevel', format: DbcFieldFormat.intType),
    const FieldDefinition(index: 44, name: 'ManaPerSecond', description: 'ManaPerSecond', format: DbcFieldFormat.intType),
    const FieldDefinition(index: 45, name: 'ManaPerSecondPerLevel', description: 'ManaPerSecondPerLevel', format: DbcFieldFormat.intType),
    const FieldDefinition(index: 46, name: 'RangeIndex', description: 'RangeIndex', format: DbcFieldFormat.intType),
    const FieldDefinition(index: 47, name: 'Speed', description: 'Speed', format: DbcFieldFormat.float),
    const FieldDefinition(index: 48, name: 'ModalNextSpell', description: 'ModalNextSpell', format: DbcFieldFormat.intType),
    const FieldDefinition(index: 49, name: 'CumulativeAura', description: 'CumulativeAura', format: DbcFieldFormat.intType),
    const FieldDefinition(index: 50, name: 'Totem0', description: 'Totem 0', format: DbcFieldFormat.intType),
    const FieldDefinition(index: 51, name: 'Totem1', description: 'Totem 1', format: DbcFieldFormat.intType),
    const FieldDefinition(index: 52, name: 'Reagent0', description: 'Reagent 0', format: DbcFieldFormat.intType),
    const FieldDefinition(index: 53, name: 'Reagent1', description: 'Reagent 1', format: DbcFieldFormat.intType),
    const FieldDefinition(index: 54, name: 'Reagent2', description: 'Reagent 2', format: DbcFieldFormat.intType),
    const FieldDefinition(index: 55, name: 'Reagent3', description: 'Reagent 3', format: DbcFieldFormat.intType),
    const FieldDefinition(index: 56, name: 'Reagent4', description: 'Reagent 4', format: DbcFieldFormat.intType),
    const FieldDefinition(index: 57, name: 'Reagent5', description: 'Reagent 5', format: DbcFieldFormat.intType),
    const FieldDefinition(index: 58, name: 'Reagent6', description: 'Reagent 6', format: DbcFieldFormat.intType),
    const FieldDefinition(index: 59, name: 'Reagent7', description: 'Reagent 7', format: DbcFieldFormat.intType),
    const FieldDefinition(index: 60, name: 'ReagentCount0', description: 'ReagentCount 0', format: DbcFieldFormat.intType),
    const FieldDefinition(index: 61, name: 'ReagentCount1', description: 'ReagentCount 1', format: DbcFieldFormat.intType),
    const FieldDefinition(index: 62, name: 'ReagentCount2', description: 'ReagentCount 2', format: DbcFieldFormat.intType),
    const FieldDefinition(index: 63, name: 'ReagentCount3', description: 'ReagentCount 3', format: DbcFieldFormat.intType),
    const FieldDefinition(index: 64, name: 'ReagentCount4', description: 'ReagentCount 4', format: DbcFieldFormat.intType),
    const FieldDefinition(index: 65, name: 'ReagentCount5', description: 'ReagentCount 5', format: DbcFieldFormat.intType),
    const FieldDefinition(index: 66, name: 'ReagentCount6', description: 'ReagentCount 6', format: DbcFieldFormat.intType),
    const FieldDefinition(index: 67, name: 'ReagentCount7', description: 'ReagentCount 7', format: DbcFieldFormat.intType),
    const FieldDefinition(index: 68, name: 'EquippedItemClass', description: 'EquippedItemClass', format: DbcFieldFormat.intType),
    const FieldDefinition(index: 69, name: 'EquippedItemSubclass', description: 'EquippedItemSubclass', format: DbcFieldFormat.intType),
    const FieldDefinition(index: 70, name: 'EquippedItemInvTypes', description: 'EquippedItemInvTypes', format: DbcFieldFormat.intType),
    const FieldDefinition(index: 71, name: 'Effect0', description: 'Effect 0', format: DbcFieldFormat.intType),
    const FieldDefinition(index: 72, name: 'Effect1', description: 'Effect 1', format: DbcFieldFormat.intType),
    const FieldDefinition(index: 73, name: 'Effect2', description: 'Effect 2', format: DbcFieldFormat.intType),
    const FieldDefinition(index: 74, name: 'EffectDieSides0', description: 'EffectDieSides 0', format: DbcFieldFormat.intType),
    const FieldDefinition(index: 75, name: 'EffectDieSides1', description: 'EffectDieSides 1', format: DbcFieldFormat.intType),
    const FieldDefinition(index: 76, name: 'EffectDieSides2', description: 'EffectDieSides 2', format: DbcFieldFormat.intType),
    const FieldDefinition(index: 77, name: 'EffectRealPointsPerLevel0', description: 'EffectRealPointsPerLevel 0', format: DbcFieldFormat.float),
    const FieldDefinition(index: 78, name: 'EffectRealPointsPerLevel1', description: 'EffectRealPointsPerLevel 1', format: DbcFieldFormat.float),
    const FieldDefinition(index: 79, name: 'EffectRealPointsPerLevel2', description: 'EffectRealPointsPerLevel 2', format: DbcFieldFormat.float),
    const FieldDefinition(index: 80, name: 'EffectBasePoints0', description: 'EffectBasePoints 0', format: DbcFieldFormat.intType),
    const FieldDefinition(index: 81, name: 'EffectBasePoints1', description: 'EffectBasePoints 1', format: DbcFieldFormat.intType),
    const FieldDefinition(index: 82, name: 'EffectBasePoints2', description: 'EffectBasePoints 2', format: DbcFieldFormat.intType),
    const FieldDefinition(index: 83, name: 'EffectMechanic0', description: 'EffectMechanic 0', format: DbcFieldFormat.intType),
    const FieldDefinition(index: 84, name: 'EffectMechanic1', description: 'EffectMechanic 1', format: DbcFieldFormat.intType),
    const FieldDefinition(index: 85, name: 'EffectMechanic2', description: 'EffectMechanic 2', format: DbcFieldFormat.intType),
    const FieldDefinition(index: 86, name: 'ImplicitTargetA0', description: 'ImplicitTargetA 0', format: DbcFieldFormat.intType),
    const FieldDefinition(index: 87, name: 'ImplicitTargetA1', description: 'ImplicitTargetA 1', format: DbcFieldFormat.intType),
    const FieldDefinition(index: 88, name: 'ImplicitTargetA2', description: 'ImplicitTargetA 2', format: DbcFieldFormat.intType),
    const FieldDefinition(index: 89, name: 'ImplicitTargetB0', description: 'ImplicitTargetB 0', format: DbcFieldFormat.intType),
    const FieldDefinition(index: 90, name: 'ImplicitTargetB1', description: 'ImplicitTargetB 1', format: DbcFieldFormat.intType),
    const FieldDefinition(index: 91, name: 'ImplicitTargetB2', description: 'ImplicitTargetB 2', format: DbcFieldFormat.intType),
    const FieldDefinition(index: 92, name: 'EffectRadiusIndex0', description: 'EffectRadiusIndex 0', format: DbcFieldFormat.intType),
    const FieldDefinition(index: 93, name: 'EffectRadiusIndex1', description: 'EffectRadiusIndex 1', format: DbcFieldFormat.intType),
    const FieldDefinition(index: 94, name: 'EffectRadiusIndex2', description: 'EffectRadiusIndex 2', format: DbcFieldFormat.intType),
    const FieldDefinition(index: 95, name: 'EffectAura0', description: 'EffectAura 0', format: DbcFieldFormat.intType),
    const FieldDefinition(index: 96, name: 'EffectAura1', description: 'EffectAura 1', format: DbcFieldFormat.intType),
    const FieldDefinition(index: 97, name: 'EffectAura2', description: 'EffectAura 2', format: DbcFieldFormat.intType),
    const FieldDefinition(index: 98, name: 'EffectAuraPeriod0', description: 'EffectAuraPeriod 0', format: DbcFieldFormat.intType),
    const FieldDefinition(index: 99, name: 'EffectAuraPeriod1', description: 'EffectAuraPeriod 1', format: DbcFieldFormat.intType),
    const FieldDefinition(index: 100, name: 'EffectAuraPeriod2', description: 'EffectAuraPeriod 2', format: DbcFieldFormat.intType),
    const FieldDefinition(index: 101, name: 'EffectAmplitude0', description: 'EffectAmplitude 0', format: DbcFieldFormat.float),
    const FieldDefinition(index: 102, name: 'EffectAmplitude1', description: 'EffectAmplitude 1', format: DbcFieldFormat.float),
    const FieldDefinition(index: 103, name: 'EffectAmplitude2', description: 'EffectAmplitude 2', format: DbcFieldFormat.float),
    const FieldDefinition(index: 104, name: 'EffectChainTargets0', description: 'EffectChainTargets 0', format: DbcFieldFormat.intType),
    const FieldDefinition(index: 105, name: 'EffectChainTargets1', description: 'EffectChainTargets 1', format: DbcFieldFormat.intType),
    const FieldDefinition(index: 106, name: 'EffectChainTargets2', description: 'EffectChainTargets 2', format: DbcFieldFormat.intType),
    const FieldDefinition(index: 107, name: 'EffectItemType0', description: 'EffectItemType 0', format: DbcFieldFormat.intType),
    const FieldDefinition(index: 108, name: 'EffectItemType1', description: 'EffectItemType 1', format: DbcFieldFormat.intType),
    const FieldDefinition(index: 109, name: 'EffectItemType2', description: 'EffectItemType 2', format: DbcFieldFormat.intType),
    const FieldDefinition(index: 110, name: 'EffectMiscValue0', description: 'EffectMiscValue 0', format: DbcFieldFormat.intType),
    const FieldDefinition(index: 111, name: 'EffectMiscValue1', description: 'EffectMiscValue 1', format: DbcFieldFormat.intType),
    const FieldDefinition(index: 112, name: 'EffectMiscValue2', description: 'EffectMiscValue 2', format: DbcFieldFormat.intType),
    const FieldDefinition(index: 113, name: 'EffectMiscValueB0', description: 'EffectMiscValueB 0', format: DbcFieldFormat.intType),
    const FieldDefinition(index: 114, name: 'EffectMiscValueB1', description: 'EffectMiscValueB 1', format: DbcFieldFormat.intType),
    const FieldDefinition(index: 115, name: 'EffectMiscValueB2', description: 'EffectMiscValueB 2', format: DbcFieldFormat.intType),
    const FieldDefinition(index: 116, name: 'EffectTriggerSpell0', description: 'EffectTriggerSpell 0', format: DbcFieldFormat.intType),
    const FieldDefinition(index: 117, name: 'EffectTriggerSpell1', description: 'EffectTriggerSpell 1', format: DbcFieldFormat.intType),
    const FieldDefinition(index: 118, name: 'EffectTriggerSpell2', description: 'EffectTriggerSpell 2', format: DbcFieldFormat.intType),
    const FieldDefinition(index: 119, name: 'EffectPointsPerCombo0', description: 'EffectPointsPerCombo 0', format: DbcFieldFormat.float),
    const FieldDefinition(index: 120, name: 'EffectPointsPerCombo1', description: 'EffectPointsPerCombo 1', format: DbcFieldFormat.float),
    const FieldDefinition(index: 121, name: 'EffectPointsPerCombo2', description: 'EffectPointsPerCombo 2', format: DbcFieldFormat.float),
    const FieldDefinition(index: 122, name: 'EffectSpellClassMaskA0', description: 'EffectSpellClassMaskA 0', format: DbcFieldFormat.intType),
    const FieldDefinition(index: 123, name: 'EffectSpellClassMaskA1', description: 'EffectSpellClassMaskA 1', format: DbcFieldFormat.intType),
    const FieldDefinition(index: 124, name: 'EffectSpellClassMaskA2', description: 'EffectSpellClassMaskA 2', format: DbcFieldFormat.intType),
    const FieldDefinition(index: 125, name: 'EffectSpellClassMaskB0', description: 'EffectSpellClassMaskB 0', format: DbcFieldFormat.intType),
    const FieldDefinition(index: 126, name: 'EffectSpellClassMaskB1', description: 'EffectSpellClassMaskB 1', format: DbcFieldFormat.intType),
    const FieldDefinition(index: 127, name: 'EffectSpellClassMaskB2', description: 'EffectSpellClassMaskB 2', format: DbcFieldFormat.intType),
    const FieldDefinition(index: 128, name: 'EffectSpellClassMaskC0', description: 'EffectSpellClassMaskC 0', format: DbcFieldFormat.intType),
    const FieldDefinition(index: 129, name: 'EffectSpellClassMaskC1', description: 'EffectSpellClassMaskC 1', format: DbcFieldFormat.intType),
    const FieldDefinition(index: 130, name: 'EffectSpellClassMaskC2', description: 'EffectSpellClassMaskC 2', format: DbcFieldFormat.intType),
    const FieldDefinition(index: 131, name: 'SpellVisualID0', description: 'SpellVisualID 0', format: DbcFieldFormat.intType),
    const FieldDefinition(index: 132, name: 'SpellVisualID1', description: 'SpellVisualID 1', format: DbcFieldFormat.intType),
    const FieldDefinition(index: 133, name: 'SpellIconID', description: 'SpellIconID', format: DbcFieldFormat.intType),
    const FieldDefinition(index: 134, name: 'ActiveIconID', description: 'ActiveIconID', format: DbcFieldFormat.intType),
    const FieldDefinition(index: 135, name: 'SpellPriority', description: 'SpellPriority', format: DbcFieldFormat.intType),
    ...createLocaleFieldsWithFlag(136, 'Name_lang', 'Name_lang'),
    ...createLocaleFieldsWithFlag(153, 'NameSubtext_lang', 'NameSubtext_lang'),
    ...createLocaleFieldsWithFlag(170, 'Description_lang', 'Description_lang'),
    ...createLocaleFieldsWithFlag(187, 'AuraDescription_lang', 'AuraDescription_lang'),
    const FieldDefinition(index: 204, name: 'ManaCostPct', description: 'ManaCostPct', format: DbcFieldFormat.intType),
    const FieldDefinition(index: 205, name: 'StartRecoveryCategory', description: 'StartRecoveryCategory', format: DbcFieldFormat.intType),
    const FieldDefinition(index: 206, name: 'StartRecoveryTime', description: 'StartRecoveryTime', format: DbcFieldFormat.intType),
    const FieldDefinition(index: 207, name: 'MaxTargetLevel', description: 'MaxTargetLevel', format: DbcFieldFormat.intType),
    const FieldDefinition(index: 208, name: 'SpellClassSet', description: 'SpellClassSet', format: DbcFieldFormat.intType),
    const FieldDefinition(index: 209, name: 'SpellClassMask0', description: 'SpellClassMask 0', format: DbcFieldFormat.intType),
    const FieldDefinition(index: 210, name: 'SpellClassMask1', description: 'SpellClassMask 1', format: DbcFieldFormat.intType),
    const FieldDefinition(index: 211, name: 'SpellClassMask2', description: 'SpellClassMask 2', format: DbcFieldFormat.intType),
    const FieldDefinition(index: 212, name: 'MaxTargets', description: 'MaxTargets', format: DbcFieldFormat.intType),
    const FieldDefinition(index: 213, name: 'DefenseType', description: 'DefenseType', format: DbcFieldFormat.intType),
    const FieldDefinition(index: 214, name: 'PreventionType', description: 'PreventionType', format: DbcFieldFormat.intType),
    const FieldDefinition(index: 215, name: 'StanceBarOrder', description: 'StanceBarOrder', format: DbcFieldFormat.intType),
    const FieldDefinition(index: 216, name: 'EffectChainAmplitude0', description: 'EffectChainAmplitude 0', format: DbcFieldFormat.float),
    const FieldDefinition(index: 217, name: 'EffectChainAmplitude1', description: 'EffectChainAmplitude 1', format: DbcFieldFormat.float),
    const FieldDefinition(index: 218, name: 'EffectChainAmplitude2', description: 'EffectChainAmplitude 2', format: DbcFieldFormat.float),
    const FieldDefinition(index: 219, name: 'MinFactionID', description: 'MinFactionID', format: DbcFieldFormat.intType),
    const FieldDefinition(index: 220, name: 'MinReputation', description: 'MinReputation', format: DbcFieldFormat.intType),
    const FieldDefinition(index: 221, name: 'RequiredAuraVision', description: 'RequiredAuraVision', format: DbcFieldFormat.intType),
    const FieldDefinition(index: 222, name: 'RequiredTotemCategoryID0', description: 'RequiredTotemCategoryID 0', format: DbcFieldFormat.intType),
    const FieldDefinition(index: 223, name: 'RequiredTotemCategoryID1', description: 'RequiredTotemCategoryID 1', format: DbcFieldFormat.intType),
    const FieldDefinition(index: 224, name: 'RequiredAreasID', description: 'RequiredAreasID', format: DbcFieldFormat.intType),
    const FieldDefinition(index: 225, name: 'SchoolMask', description: 'SchoolMask', format: DbcFieldFormat.intType),
    const FieldDefinition(index: 226, name: 'RuneCostID', description: 'RuneCostID', format: DbcFieldFormat.intType),
    const FieldDefinition(index: 227, name: 'SpellMissileID', description: 'SpellMissileID', format: DbcFieldFormat.intType),
    const FieldDefinition(index: 228, name: 'PowerDisplayID', description: 'PowerDisplayID', format: DbcFieldFormat.intType),
    const FieldDefinition(index: 229, name: 'EffectBonusCoefficient0', description: 'EffectBonusCoefficient 0', format: DbcFieldFormat.float),
    const FieldDefinition(index: 230, name: 'EffectBonusCoefficient1', description: 'EffectBonusCoefficient 1', format: DbcFieldFormat.float),
    const FieldDefinition(index: 231, name: 'EffectBonusCoefficient2', description: 'EffectBonusCoefficient 2', format: DbcFieldFormat.float),
    const FieldDefinition(index: 232, name: 'DescriptionVariablesID', description: 'DescriptionVariablesID', format: DbcFieldFormat.intType),
    const FieldDefinition(index: 233, name: 'Difficulty', description: 'Difficulty', format: DbcFieldFormat.intType),
  ],
);
