import 'package:warcrafty/src/core/field_definition.dart';
import 'package:warcrafty/src/core/structure_definition.dart';
import 'package:warcrafty/src/core/field_format.dart';

/// SpellChainEffects 结构定义
///
/// 基于 WoWDBDefs 定义，版本 3.3.5.12340
const spellChainEffects = DbcStructureDefinition(
  name: 'SpellChainEffects',
  format: 'nffffiisiifiiffffffffffffffffffffffffffbbbbbsiff',
  fields: [
    FieldDefinition(index: 0, name: 'ID', description: 'ID', format: DbcFieldFormat.indexField),
    FieldDefinition(index: 1, name: 'AvgSegLen', description: 'AvgSegLen', format: DbcFieldFormat.float),
    FieldDefinition(index: 2, name: 'Width', description: 'Width', format: DbcFieldFormat.float),
    FieldDefinition(index: 3, name: 'NoiseScale', description: 'NoiseScale', format: DbcFieldFormat.float),
    FieldDefinition(index: 4, name: 'TexCoordScale', description: 'TexCoordScale', format: DbcFieldFormat.float),
    FieldDefinition(index: 5, name: 'SegDuration', description: 'SegDuration', format: DbcFieldFormat.intType),
    FieldDefinition(index: 6, name: 'SegDelay', description: 'SegDelay', format: DbcFieldFormat.intType),
    FieldDefinition(index: 7, name: 'Texture', description: 'Texture', format: DbcFieldFormat.string),
    FieldDefinition(index: 8, name: 'Flags', description: 'Flags', format: DbcFieldFormat.intType),
    FieldDefinition(index: 9, name: 'JointCount', description: 'JointCount', format: DbcFieldFormat.intType),
    FieldDefinition(index: 10, name: 'JointOffsetRadius', description: 'JointOffsetRadius', format: DbcFieldFormat.float),
    FieldDefinition(index: 11, name: 'JointsPerMinorJoint', description: 'JointsPerMinorJoint', format: DbcFieldFormat.intType),
    FieldDefinition(index: 12, name: 'MinorJointsPerMajorJoint', description: 'MinorJointsPerMajorJoint', format: DbcFieldFormat.intType),
    FieldDefinition(index: 13, name: 'MinorJointScale', description: 'MinorJointScale', format: DbcFieldFormat.float),
    FieldDefinition(index: 14, name: 'MajorJointScale', description: 'MajorJointScale', format: DbcFieldFormat.float),
    FieldDefinition(index: 15, name: 'JointMoveSpeed', description: 'JointMoveSpeed', format: DbcFieldFormat.float),
    FieldDefinition(index: 16, name: 'JointSmoothness', description: 'JointSmoothness', format: DbcFieldFormat.float),
    FieldDefinition(index: 17, name: 'MinDurationBetweenJointJumps', description: 'MinDurationBetweenJointJumps', format: DbcFieldFormat.float),
    FieldDefinition(index: 18, name: 'MaxDurationBetweenJointJumps', description: 'MaxDurationBetweenJointJumps', format: DbcFieldFormat.float),
    FieldDefinition(index: 19, name: 'WaveHeight', description: 'WaveHeight', format: DbcFieldFormat.float),
    FieldDefinition(index: 20, name: 'WaveFreq', description: 'WaveFreq', format: DbcFieldFormat.float),
    FieldDefinition(index: 21, name: 'WaveSpeed', description: 'WaveSpeed', format: DbcFieldFormat.float),
    FieldDefinition(index: 22, name: 'MinWaveAngle', description: 'MinWaveAngle', format: DbcFieldFormat.float),
    FieldDefinition(index: 23, name: 'MaxWaveAngle', description: 'MaxWaveAngle', format: DbcFieldFormat.float),
    FieldDefinition(index: 24, name: 'MinWaveSpin', description: 'MinWaveSpin', format: DbcFieldFormat.float),
    FieldDefinition(index: 25, name: 'MaxWaveSpin', description: 'MaxWaveSpin', format: DbcFieldFormat.float),
    FieldDefinition(index: 26, name: 'ArcHeight', description: 'ArcHeight', format: DbcFieldFormat.float),
    FieldDefinition(index: 27, name: 'MinArcAngle', description: 'MinArcAngle', format: DbcFieldFormat.float),
    FieldDefinition(index: 28, name: 'MaxArcAngle', description: 'MaxArcAngle', format: DbcFieldFormat.float),
    FieldDefinition(index: 29, name: 'MinArcSpin', description: 'MinArcSpin', format: DbcFieldFormat.float),
    FieldDefinition(index: 30, name: 'MaxArcSpin', description: 'MaxArcSpin', format: DbcFieldFormat.float),
    FieldDefinition(index: 31, name: 'DelayBetweenEffects', description: 'DelayBetweenEffects', format: DbcFieldFormat.float),
    FieldDefinition(index: 32, name: 'MinFlickerOnDuration', description: 'MinFlickerOnDuration', format: DbcFieldFormat.float),
    FieldDefinition(index: 33, name: 'MaxFlickerOnDuration', description: 'MaxFlickerOnDuration', format: DbcFieldFormat.float),
    FieldDefinition(index: 34, name: 'MinFlickerOffDuration', description: 'MinFlickerOffDuration', format: DbcFieldFormat.float),
    FieldDefinition(index: 35, name: 'MaxFlickerOffDuration', description: 'MaxFlickerOffDuration', format: DbcFieldFormat.float),
    FieldDefinition(index: 36, name: 'PulseSpeed', description: 'PulseSpeed', format: DbcFieldFormat.float),
    FieldDefinition(index: 37, name: 'PulseOnLength', description: 'PulseOnLength', format: DbcFieldFormat.float),
    FieldDefinition(index: 38, name: 'PulseFadeLength', description: 'PulseFadeLength', format: DbcFieldFormat.float),
    FieldDefinition(index: 39, name: 'Alpha', description: 'Alpha', format: DbcFieldFormat.byte),
    FieldDefinition(index: 40, name: 'Red', description: 'Red', format: DbcFieldFormat.byte),
    FieldDefinition(index: 41, name: 'Green', description: 'Green', format: DbcFieldFormat.byte),
    FieldDefinition(index: 42, name: 'Blue', description: 'Blue', format: DbcFieldFormat.byte),
    FieldDefinition(index: 43, name: 'BlendMode', description: 'BlendMode', format: DbcFieldFormat.byte),
    FieldDefinition(index: 44, name: 'Combo', description: 'Combo', format: DbcFieldFormat.string),
    FieldDefinition(index: 45, name: 'RenderLayer', description: 'RenderLayer', format: DbcFieldFormat.intType),
    FieldDefinition(index: 46, name: 'TextureLength', description: 'TextureLength', format: DbcFieldFormat.float),
    FieldDefinition(index: 47, name: 'WavePhase', description: 'WavePhase', format: DbcFieldFormat.float),
  ],
);
