import 'package:warcrafty/src/schema/field.dart';
import 'package:warcrafty/src/schema/schema.dart';

/// SpellChainEffects 结构定义
///
/// 基于 WoWDBDefs 定义，版本 3.3.5.12340
const spellChainEffects = DbcSchema(
  name: 'SpellChainEffects',
  format: 'nffffiisiifiiffffffffffffffffffffffffffbbbbbsiff',
  fields: [
    Field(index: 0, name: 'ID', description: 'ID', type: FieldType.id),
    Field(index: 1, name: 'AvgSegLen', description: 'AvgSegLen', type: FieldType.float),
    Field(index: 2, name: 'Width', description: 'Width', type: FieldType.float),
    Field(index: 3, name: 'NoiseScale', description: 'NoiseScale', type: FieldType.float),
    Field(index: 4, name: 'TexCoordScale', description: 'TexCoordScale', type: FieldType.float),
    Field(index: 5, name: 'SegDuration', description: 'SegDuration', type: FieldType.int32),
    Field(index: 6, name: 'SegDelay', description: 'SegDelay', type: FieldType.int32),
    Field(index: 7, name: 'Texture', description: 'Texture', type: FieldType.string),
    Field(index: 8, name: 'Flags', description: 'Flags', type: FieldType.int32),
    Field(index: 9, name: 'JointCount', description: 'JointCount', type: FieldType.int32),
    Field(index: 10, name: 'JointOffsetRadius', description: 'JointOffsetRadius', type: FieldType.float),
    Field(index: 11, name: 'JointsPerMinorJoint', description: 'JointsPerMinorJoint', type: FieldType.int32),
    Field(index: 12, name: 'MinorJointsPerMajorJoint', description: 'MinorJointsPerMajorJoint', type: FieldType.int32),
    Field(index: 13, name: 'MinorJointScale', description: 'MinorJointScale', type: FieldType.float),
    Field(index: 14, name: 'MajorJointScale', description: 'MajorJointScale', type: FieldType.float),
    Field(index: 15, name: 'JointMoveSpeed', description: 'JointMoveSpeed', type: FieldType.float),
    Field(index: 16, name: 'JointSmoothness', description: 'JointSmoothness', type: FieldType.float),
    Field(index: 17, name: 'MinDurationBetweenJointJumps', description: 'MinDurationBetweenJointJumps', type: FieldType.float),
    Field(index: 18, name: 'MaxDurationBetweenJointJumps', description: 'MaxDurationBetweenJointJumps', type: FieldType.float),
    Field(index: 19, name: 'WaveHeight', description: 'WaveHeight', type: FieldType.float),
    Field(index: 20, name: 'WaveFreq', description: 'WaveFreq', type: FieldType.float),
    Field(index: 21, name: 'WaveSpeed', description: 'WaveSpeed', type: FieldType.float),
    Field(index: 22, name: 'MinWaveAngle', description: 'MinWaveAngle', type: FieldType.float),
    Field(index: 23, name: 'MaxWaveAngle', description: 'MaxWaveAngle', type: FieldType.float),
    Field(index: 24, name: 'MinWaveSpin', description: 'MinWaveSpin', type: FieldType.float),
    Field(index: 25, name: 'MaxWaveSpin', description: 'MaxWaveSpin', type: FieldType.float),
    Field(index: 26, name: 'ArcHeight', description: 'ArcHeight', type: FieldType.float),
    Field(index: 27, name: 'MinArcAngle', description: 'MinArcAngle', type: FieldType.float),
    Field(index: 28, name: 'MaxArcAngle', description: 'MaxArcAngle', type: FieldType.float),
    Field(index: 29, name: 'MinArcSpin', description: 'MinArcSpin', type: FieldType.float),
    Field(index: 30, name: 'MaxArcSpin', description: 'MaxArcSpin', type: FieldType.float),
    Field(index: 31, name: 'DelayBetweenEffects', description: 'DelayBetweenEffects', type: FieldType.float),
    Field(index: 32, name: 'MinFlickerOnDuration', description: 'MinFlickerOnDuration', type: FieldType.float),
    Field(index: 33, name: 'MaxFlickerOnDuration', description: 'MaxFlickerOnDuration', type: FieldType.float),
    Field(index: 34, name: 'MinFlickerOffDuration', description: 'MinFlickerOffDuration', type: FieldType.float),
    Field(index: 35, name: 'MaxFlickerOffDuration', description: 'MaxFlickerOffDuration', type: FieldType.float),
    Field(index: 36, name: 'PulseSpeed', description: 'PulseSpeed', type: FieldType.float),
    Field(index: 37, name: 'PulseOnLength', description: 'PulseOnLength', type: FieldType.float),
    Field(index: 38, name: 'PulseFadeLength', description: 'PulseFadeLength', type: FieldType.float),
    Field(index: 39, name: 'Alpha', description: 'Alpha', type: FieldType.uint8),
    Field(index: 40, name: 'Red', description: 'Red', type: FieldType.uint8),
    Field(index: 41, name: 'Green', description: 'Green', type: FieldType.uint8),
    Field(index: 42, name: 'Blue', description: 'Blue', type: FieldType.uint8),
    Field(index: 43, name: 'BlendMode', description: 'BlendMode', type: FieldType.uint8),
    Field(index: 44, name: 'Combo', description: 'Combo', type: FieldType.string),
    Field(index: 45, name: 'RenderLayer', description: 'RenderLayer', type: FieldType.int32),
    Field(index: 46, name: 'TextureLength', description: 'TextureLength', type: FieldType.float),
    Field(index: 47, name: 'WavePhase', description: 'WavePhase', type: FieldType.float),
  ],
);
