import 'package:warcrafty/src/schema/field.dart';
import 'package:warcrafty/src/schema/schema.dart';

/// CreatureSoundData 结构定义
///
/// 基于 WoWDBDefs 定义，版本 3.3.5.12340
const creatureSoundData = DbcSchema(
  name: 'CreatureSoundData',
  format: 'niiiiiiiiiiiiiiiiiiiiiiiiiiiiiiffiiiii',
  fields: [
    Field(index: 0, name: 'ID', description: 'ID', type: FieldType.id),
    Field(index: 1, name: 'SoundExertionID', description: 'SoundExertionID', type: FieldType.int32),
    Field(index: 2, name: 'SoundExertionCriticalID', description: 'SoundExertionCriticalID', type: FieldType.int32),
    Field(index: 3, name: 'SoundInjuryID', description: 'SoundInjuryID', type: FieldType.int32),
    Field(index: 4, name: 'SoundInjuryCriticalID', description: 'SoundInjuryCriticalID', type: FieldType.int32),
    Field(index: 5, name: 'SoundInjuryCrushingBlowID', description: 'SoundInjuryCrushingBlowID', type: FieldType.int32),
    Field(index: 6, name: 'SoundDeathID', description: 'SoundDeathID', type: FieldType.int32),
    Field(index: 7, name: 'SoundStunID', description: 'SoundStunID', type: FieldType.int32),
    Field(index: 8, name: 'SoundStandID', description: 'SoundStandID', type: FieldType.int32),
    Field(index: 9, name: 'SoundFootstepID', description: 'SoundFootstepID', type: FieldType.int32),
    Field(index: 10, name: 'SoundAggroID', description: 'SoundAggroID', type: FieldType.int32),
    Field(index: 11, name: 'SoundWingFlapID', description: 'SoundWingFlapID', type: FieldType.int32),
    Field(index: 12, name: 'SoundWingGlideID', description: 'SoundWingGlideID', type: FieldType.int32),
    Field(index: 13, name: 'SoundAlertID', description: 'SoundAlertID', type: FieldType.int32),
    Field(index: 14, name: 'SoundFidget0', description: 'SoundFidget 0', type: FieldType.int32),
    Field(index: 15, name: 'SoundFidget1', description: 'SoundFidget 1', type: FieldType.int32),
    Field(index: 16, name: 'SoundFidget2', description: 'SoundFidget 2', type: FieldType.int32),
    Field(index: 17, name: 'SoundFidget3', description: 'SoundFidget 3', type: FieldType.int32),
    Field(index: 18, name: 'SoundFidget4', description: 'SoundFidget 4', type: FieldType.int32),
    Field(index: 19, name: 'CustomAttack0', description: 'CustomAttack 0', type: FieldType.int32),
    Field(index: 20, name: 'CustomAttack1', description: 'CustomAttack 1', type: FieldType.int32),
    Field(index: 21, name: 'CustomAttack2', description: 'CustomAttack 2', type: FieldType.int32),
    Field(index: 22, name: 'CustomAttack3', description: 'CustomAttack 3', type: FieldType.int32),
    Field(index: 23, name: 'NPCSoundID', description: 'NPCSoundID', type: FieldType.int32),
    Field(index: 24, name: 'LoopSoundID', description: 'LoopSoundID', type: FieldType.int32),
    Field(index: 25, name: 'CreatureImpactType', description: 'CreatureImpactType', type: FieldType.int32),
    Field(index: 26, name: 'SoundJumpStartID', description: 'SoundJumpStartID', type: FieldType.int32),
    Field(index: 27, name: 'SoundJumpEndID', description: 'SoundJumpEndID', type: FieldType.int32),
    Field(index: 28, name: 'SoundPetAttackID', description: 'SoundPetAttackID', type: FieldType.int32),
    Field(index: 29, name: 'SoundPetOrderID', description: 'SoundPetOrderID', type: FieldType.int32),
    Field(index: 30, name: 'SoundPetDismissID', description: 'SoundPetDismissID', type: FieldType.int32),
    Field(index: 31, name: 'FidgetDelaySecondsMin', description: 'FidgetDelaySecondsMin', type: FieldType.float),
    Field(index: 32, name: 'FidgetDelaySecondsMax', description: 'FidgetDelaySecondsMax', type: FieldType.float),
    Field(index: 33, name: 'BirthSoundID', description: 'BirthSoundID', type: FieldType.int32),
    Field(index: 34, name: 'SpellCastDirectedSoundID', description: 'SpellCastDirectedSoundID', type: FieldType.int32),
    Field(index: 35, name: 'SubmergeSoundID', description: 'SubmergeSoundID', type: FieldType.int32),
    Field(index: 36, name: 'SubmergedSoundID', description: 'SubmergedSoundID', type: FieldType.int32),
    Field(index: 37, name: 'CreatureSoundDataIDPet', description: 'CreatureSoundDataIDPet', type: FieldType.int32),
  ],
);
