import 'package:warcrafty/src/internal/field.dart';
import 'package:warcrafty/src/internal/schema.dart';

/// Holidays 结构定义
///
/// 基于 WoWDBDefs 定义，版本 3.3.5.12340
const holidays = DbcSchema(
  name: 'Holidays',
  format: 'niiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiisiii',
  fields: [
    Field(index: 0, name: 'ID', description: 'ID', type: FieldType.id),
    Field(index: 1, name: 'Duration0', description: 'Duration 0', type: FieldType.int32),
    Field(index: 2, name: 'Duration1', description: 'Duration 1', type: FieldType.int32),
    Field(index: 3, name: 'Duration2', description: 'Duration 2', type: FieldType.int32),
    Field(index: 4, name: 'Duration3', description: 'Duration 3', type: FieldType.int32),
    Field(index: 5, name: 'Duration4', description: 'Duration 4', type: FieldType.int32),
    Field(index: 6, name: 'Duration5', description: 'Duration 5', type: FieldType.int32),
    Field(index: 7, name: 'Duration6', description: 'Duration 6', type: FieldType.int32),
    Field(index: 8, name: 'Duration7', description: 'Duration 7', type: FieldType.int32),
    Field(index: 9, name: 'Duration8', description: 'Duration 8', type: FieldType.int32),
    Field(index: 10, name: 'Duration9', description: 'Duration 9', type: FieldType.int32),
    Field(index: 11, name: 'Date0', description: 'Date 0', type: FieldType.int32),
    Field(index: 12, name: 'Date1', description: 'Date 1', type: FieldType.int32),
    Field(index: 13, name: 'Date2', description: 'Date 2', type: FieldType.int32),
    Field(index: 14, name: 'Date3', description: 'Date 3', type: FieldType.int32),
    Field(index: 15, name: 'Date4', description: 'Date 4', type: FieldType.int32),
    Field(index: 16, name: 'Date5', description: 'Date 5', type: FieldType.int32),
    Field(index: 17, name: 'Date6', description: 'Date 6', type: FieldType.int32),
    Field(index: 18, name: 'Date7', description: 'Date 7', type: FieldType.int32),
    Field(index: 19, name: 'Date8', description: 'Date 8', type: FieldType.int32),
    Field(index: 20, name: 'Date9', description: 'Date 9', type: FieldType.int32),
    Field(index: 21, name: 'Date10', description: 'Date 10', type: FieldType.int32),
    Field(index: 22, name: 'Date11', description: 'Date 11', type: FieldType.int32),
    Field(index: 23, name: 'Date12', description: 'Date 12', type: FieldType.int32),
    Field(index: 24, name: 'Date13', description: 'Date 13', type: FieldType.int32),
    Field(index: 25, name: 'Date14', description: 'Date 14', type: FieldType.int32),
    Field(index: 26, name: 'Date15', description: 'Date 15', type: FieldType.int32),
    Field(index: 27, name: 'Date16', description: 'Date 16', type: FieldType.int32),
    Field(index: 28, name: 'Date17', description: 'Date 17', type: FieldType.int32),
    Field(index: 29, name: 'Date18', description: 'Date 18', type: FieldType.int32),
    Field(index: 30, name: 'Date19', description: 'Date 19', type: FieldType.int32),
    Field(index: 31, name: 'Date20', description: 'Date 20', type: FieldType.int32),
    Field(index: 32, name: 'Date21', description: 'Date 21', type: FieldType.int32),
    Field(index: 33, name: 'Date22', description: 'Date 22', type: FieldType.int32),
    Field(index: 34, name: 'Date23', description: 'Date 23', type: FieldType.int32),
    Field(index: 35, name: 'Date24', description: 'Date 24', type: FieldType.int32),
    Field(index: 36, name: 'Date25', description: 'Date 25', type: FieldType.int32),
    Field(index: 37, name: 'Region', description: 'Region', type: FieldType.int32),
    Field(index: 38, name: 'Looping', description: 'Looping', type: FieldType.int32),
    Field(index: 39, name: 'CalendarFlags0', description: 'CalendarFlags 0', type: FieldType.int32),
    Field(index: 40, name: 'CalendarFlags1', description: 'CalendarFlags 1', type: FieldType.int32),
    Field(index: 41, name: 'CalendarFlags2', description: 'CalendarFlags 2', type: FieldType.int32),
    Field(index: 42, name: 'CalendarFlags3', description: 'CalendarFlags 3', type: FieldType.int32),
    Field(index: 43, name: 'CalendarFlags4', description: 'CalendarFlags 4', type: FieldType.int32),
    Field(index: 44, name: 'CalendarFlags5', description: 'CalendarFlags 5', type: FieldType.int32),
    Field(index: 45, name: 'CalendarFlags6', description: 'CalendarFlags 6', type: FieldType.int32),
    Field(index: 46, name: 'CalendarFlags7', description: 'CalendarFlags 7', type: FieldType.int32),
    Field(index: 47, name: 'CalendarFlags8', description: 'CalendarFlags 8', type: FieldType.int32),
    Field(index: 48, name: 'CalendarFlags9', description: 'CalendarFlags 9', type: FieldType.int32),
    Field(index: 49, name: 'HolidayNameID', description: 'HolidayNameID', type: FieldType.int32),
    Field(index: 50, name: 'HolidayDescriptionID', description: 'HolidayDescriptionID', type: FieldType.int32),
    Field(index: 51, name: 'TextureFileName', description: 'TextureFileName', type: FieldType.string),
    Field(index: 52, name: 'Priority', description: 'Priority', type: FieldType.int32),
    Field(index: 53, name: 'CalendarFilterType', description: 'CalendarFilterType', type: FieldType.int32),
    Field(index: 54, name: 'Flags', description: 'Flags', type: FieldType.int32),
  ],
);
