import 'package:warcrafty/src/definition/base/field_definition.dart';
import 'package:warcrafty/src/definition/base/structure_definition.dart';
import 'package:warcrafty/src/core/field_format.dart';

/// Holidays 结构定义
///
/// 基于 WoWDBDefs 定义，版本 3.3.5.12340
const holidays = DbcStructureDefinition(
  name: 'Holidays',
  format: 'niiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiisiii',
  fields: [
    FieldDefinition(index: 0, name: 'ID', description: 'ID', format: DbcFieldFormat.indexField),
    FieldDefinition(index: 1, name: 'Duration0', description: 'Duration 0', format: DbcFieldFormat.intType),
    FieldDefinition(index: 2, name: 'Duration1', description: 'Duration 1', format: DbcFieldFormat.intType),
    FieldDefinition(index: 3, name: 'Duration2', description: 'Duration 2', format: DbcFieldFormat.intType),
    FieldDefinition(index: 4, name: 'Duration3', description: 'Duration 3', format: DbcFieldFormat.intType),
    FieldDefinition(index: 5, name: 'Duration4', description: 'Duration 4', format: DbcFieldFormat.intType),
    FieldDefinition(index: 6, name: 'Duration5', description: 'Duration 5', format: DbcFieldFormat.intType),
    FieldDefinition(index: 7, name: 'Duration6', description: 'Duration 6', format: DbcFieldFormat.intType),
    FieldDefinition(index: 8, name: 'Duration7', description: 'Duration 7', format: DbcFieldFormat.intType),
    FieldDefinition(index: 9, name: 'Duration8', description: 'Duration 8', format: DbcFieldFormat.intType),
    FieldDefinition(index: 10, name: 'Duration9', description: 'Duration 9', format: DbcFieldFormat.intType),
    FieldDefinition(index: 11, name: 'Date0', description: 'Date 0', format: DbcFieldFormat.intType),
    FieldDefinition(index: 12, name: 'Date1', description: 'Date 1', format: DbcFieldFormat.intType),
    FieldDefinition(index: 13, name: 'Date2', description: 'Date 2', format: DbcFieldFormat.intType),
    FieldDefinition(index: 14, name: 'Date3', description: 'Date 3', format: DbcFieldFormat.intType),
    FieldDefinition(index: 15, name: 'Date4', description: 'Date 4', format: DbcFieldFormat.intType),
    FieldDefinition(index: 16, name: 'Date5', description: 'Date 5', format: DbcFieldFormat.intType),
    FieldDefinition(index: 17, name: 'Date6', description: 'Date 6', format: DbcFieldFormat.intType),
    FieldDefinition(index: 18, name: 'Date7', description: 'Date 7', format: DbcFieldFormat.intType),
    FieldDefinition(index: 19, name: 'Date8', description: 'Date 8', format: DbcFieldFormat.intType),
    FieldDefinition(index: 20, name: 'Date9', description: 'Date 9', format: DbcFieldFormat.intType),
    FieldDefinition(index: 21, name: 'Date10', description: 'Date 10', format: DbcFieldFormat.intType),
    FieldDefinition(index: 22, name: 'Date11', description: 'Date 11', format: DbcFieldFormat.intType),
    FieldDefinition(index: 23, name: 'Date12', description: 'Date 12', format: DbcFieldFormat.intType),
    FieldDefinition(index: 24, name: 'Date13', description: 'Date 13', format: DbcFieldFormat.intType),
    FieldDefinition(index: 25, name: 'Date14', description: 'Date 14', format: DbcFieldFormat.intType),
    FieldDefinition(index: 26, name: 'Date15', description: 'Date 15', format: DbcFieldFormat.intType),
    FieldDefinition(index: 27, name: 'Date16', description: 'Date 16', format: DbcFieldFormat.intType),
    FieldDefinition(index: 28, name: 'Date17', description: 'Date 17', format: DbcFieldFormat.intType),
    FieldDefinition(index: 29, name: 'Date18', description: 'Date 18', format: DbcFieldFormat.intType),
    FieldDefinition(index: 30, name: 'Date19', description: 'Date 19', format: DbcFieldFormat.intType),
    FieldDefinition(index: 31, name: 'Date20', description: 'Date 20', format: DbcFieldFormat.intType),
    FieldDefinition(index: 32, name: 'Date21', description: 'Date 21', format: DbcFieldFormat.intType),
    FieldDefinition(index: 33, name: 'Date22', description: 'Date 22', format: DbcFieldFormat.intType),
    FieldDefinition(index: 34, name: 'Date23', description: 'Date 23', format: DbcFieldFormat.intType),
    FieldDefinition(index: 35, name: 'Date24', description: 'Date 24', format: DbcFieldFormat.intType),
    FieldDefinition(index: 36, name: 'Date25', description: 'Date 25', format: DbcFieldFormat.intType),
    FieldDefinition(index: 37, name: 'Region', description: 'Region', format: DbcFieldFormat.intType),
    FieldDefinition(index: 38, name: 'Looping', description: 'Looping', format: DbcFieldFormat.intType),
    FieldDefinition(index: 39, name: 'CalendarFlags0', description: 'CalendarFlags 0', format: DbcFieldFormat.intType),
    FieldDefinition(index: 40, name: 'CalendarFlags1', description: 'CalendarFlags 1', format: DbcFieldFormat.intType),
    FieldDefinition(index: 41, name: 'CalendarFlags2', description: 'CalendarFlags 2', format: DbcFieldFormat.intType),
    FieldDefinition(index: 42, name: 'CalendarFlags3', description: 'CalendarFlags 3', format: DbcFieldFormat.intType),
    FieldDefinition(index: 43, name: 'CalendarFlags4', description: 'CalendarFlags 4', format: DbcFieldFormat.intType),
    FieldDefinition(index: 44, name: 'CalendarFlags5', description: 'CalendarFlags 5', format: DbcFieldFormat.intType),
    FieldDefinition(index: 45, name: 'CalendarFlags6', description: 'CalendarFlags 6', format: DbcFieldFormat.intType),
    FieldDefinition(index: 46, name: 'CalendarFlags7', description: 'CalendarFlags 7', format: DbcFieldFormat.intType),
    FieldDefinition(index: 47, name: 'CalendarFlags8', description: 'CalendarFlags 8', format: DbcFieldFormat.intType),
    FieldDefinition(index: 48, name: 'CalendarFlags9', description: 'CalendarFlags 9', format: DbcFieldFormat.intType),
    FieldDefinition(index: 49, name: 'HolidayNameID', description: 'HolidayNameID', format: DbcFieldFormat.intType),
    FieldDefinition(index: 50, name: 'HolidayDescriptionID', description: 'HolidayDescriptionID', format: DbcFieldFormat.intType),
    FieldDefinition(index: 51, name: 'TextureFileName', description: 'TextureFileName', format: DbcFieldFormat.string),
    FieldDefinition(index: 52, name: 'Priority', description: 'Priority', format: DbcFieldFormat.intType),
    FieldDefinition(index: 53, name: 'CalendarFilterType', description: 'CalendarFilterType', format: DbcFieldFormat.intType),
    FieldDefinition(index: 54, name: 'Flags', description: 'Flags', format: DbcFieldFormat.intType),
  ],
);
