import 'package:warcrafty/src/internal/field.dart';
import 'package:warcrafty/src/internal/schema.dart';

/// LiquidType 结构定义
///
/// 基于 WoWDBDefs 定义，版本 3.3.5.12340
const liquidType = DbcSchema(
  name: 'LiquidType',
  format: 'nsiiiiffffifiiissssssiiffffffffffffffffffiiii',
  fields: [
    Field(index: 0, name: 'ID', description: 'ID', type: FieldType.id),
    Field(index: 1, name: 'Name', description: 'Name', type: FieldType.string),
    Field(index: 2, name: 'Flags', description: 'Flags', type: FieldType.int32),
    Field(index: 3, name: 'SoundBank', description: 'SoundBank', type: FieldType.int32),
    Field(index: 4, name: 'SoundID', description: 'SoundID', type: FieldType.int32),
    Field(index: 5, name: 'SpellID', description: 'SpellID', type: FieldType.int32),
    Field(index: 6, name: 'MaxDarkenDepth', description: 'MaxDarkenDepth', type: FieldType.float),
    Field(index: 7, name: 'FogDarkenIntensity', description: 'FogDarkenIntensity', type: FieldType.float),
    Field(index: 8, name: 'AmbDarkenIntensity', description: 'AmbDarkenIntensity', type: FieldType.float),
    Field(index: 9, name: 'DirDarkenIntensity', description: 'DirDarkenIntensity', type: FieldType.float),
    Field(index: 10, name: 'LightID', description: 'LightID', type: FieldType.int32),
    Field(index: 11, name: 'ParticleScale', description: 'ParticleScale', type: FieldType.float),
    Field(index: 12, name: 'ParticleMovement', description: 'ParticleMovement', type: FieldType.int32),
    Field(index: 13, name: 'ParticleTexSlots', description: 'ParticleTexSlots', type: FieldType.int32),
    Field(index: 14, name: 'MaterialID', description: 'MaterialID', type: FieldType.int32),
    Field(index: 15, name: 'Texture0', description: 'Texture 0', type: FieldType.string),
    Field(index: 16, name: 'Texture1', description: 'Texture 1', type: FieldType.string),
    Field(index: 17, name: 'Texture2', description: 'Texture 2', type: FieldType.string),
    Field(index: 18, name: 'Texture3', description: 'Texture 3', type: FieldType.string),
    Field(index: 19, name: 'Texture4', description: 'Texture 4', type: FieldType.string),
    Field(index: 20, name: 'Texture5', description: 'Texture 5', type: FieldType.string),
    Field(index: 21, name: 'Color0', description: 'Color 0', type: FieldType.int32),
    Field(index: 22, name: 'Color1', description: 'Color 1', type: FieldType.int32),
    Field(index: 23, name: 'Float0', description: 'Float 0', type: FieldType.float),
    Field(index: 24, name: 'Float1', description: 'Float 1', type: FieldType.float),
    Field(index: 25, name: 'Float2', description: 'Float 2', type: FieldType.float),
    Field(index: 26, name: 'Float3', description: 'Float 3', type: FieldType.float),
    Field(index: 27, name: 'Float4', description: 'Float 4', type: FieldType.float),
    Field(index: 28, name: 'Float5', description: 'Float 5', type: FieldType.float),
    Field(index: 29, name: 'Float6', description: 'Float 6', type: FieldType.float),
    Field(index: 30, name: 'Float7', description: 'Float 7', type: FieldType.float),
    Field(index: 31, name: 'Float8', description: 'Float 8', type: FieldType.float),
    Field(index: 32, name: 'Float9', description: 'Float 9', type: FieldType.float),
    Field(index: 33, name: 'Float10', description: 'Float 10', type: FieldType.float),
    Field(index: 34, name: 'Float11', description: 'Float 11', type: FieldType.float),
    Field(index: 35, name: 'Float12', description: 'Float 12', type: FieldType.float),
    Field(index: 36, name: 'Float13', description: 'Float 13', type: FieldType.float),
    Field(index: 37, name: 'Float14', description: 'Float 14', type: FieldType.float),
    Field(index: 38, name: 'Float15', description: 'Float 15', type: FieldType.float),
    Field(index: 39, name: 'Float16', description: 'Float 16', type: FieldType.float),
    Field(index: 40, name: 'Float17', description: 'Float 17', type: FieldType.float),
    Field(index: 41, name: 'Int0', description: 'Int 0', type: FieldType.int32),
    Field(index: 42, name: 'Int1', description: 'Int 1', type: FieldType.int32),
    Field(index: 43, name: 'Int2', description: 'Int 2', type: FieldType.int32),
    Field(index: 44, name: 'Int3', description: 'Int 3', type: FieldType.int32),
  ],
);
